%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% A template for Wiley article submissions developed by
% Overleaf for the Overleaf-Wiley pilot which ran
% during 2017 and 2018.
%
% This template is no longer supported, but is provided
% for historical reference. Last updated January 2019.
%
% Please note that whilst this template provides a
% preview of the typeset manuscript for submission, it
% will not necessarily be the final publication layout.
%
% Document class options:
% =======================
% blind: Anonymise all author, affiliation, correspondence
%        and funding information.
%
% lineno: Adds line numbers.
%
% serif: Sets the body font to be serif.
%
% twocolumn: Sets the body text in two-column layout.
%
% num-refs: Uses numerical citation and references style
%           (Vancouver-authoryear).
%
% alpha-refs: Uses author-year citation and references style
%             (rss).
%
% Using other bibliography styles:
% =======================
%
% To specify a different bibiography style
%
% 1) Do not use either num-refs or alpha-refs in documentclass.
% 2) Load natbib package with the options set as needed.
% 3) Use the \bibliographystyle command to specify the style
%
% Included NJD styles are:
%   WileyNJD-ACS
%   WileyNJD-AMA
%   WileyNJD-AMS
%   WileyNJD-APA
%   WileyNJD-Harvard
%   WileyNJD-VANCOUVER
%
% or you may upload an alternative .bst file
% (if requested by the journal).
%
% Examples:
% =======================
%% Example: Using numerical, sort-by-authors citations.
\documentclass[alpha-refs]{wiley-article-rmd}

%% Example: Using author-year citations and anonymising submission
% \documentclass[blind,alpha-refs]{wiley-article}

%% Example: Using unsrtnat for numerical, in-sequence citations
% \documentclass{wiley-article}
% \usepackage[numbers]{natbib}
% \bibliographystyle{unsrtnat}

%% Example: Using WileyNJD-AMA reference style and superscript
%%          citations, two-column and serif fonts for AIChE
% \documentclass[serif,twocolumn,lineno]{wiley-article}
% \usepackage[super]{natbib}
% \bibliographystyle{WileyNJD-AMA}
% \makeatletter
% \renewcommand{\@biblabel}[1]{#1.}
% \makeatother

% Add additional packages here if required
\usepackage[alsoload=synchem]{siunitx}

% Update article type if known
  \papertype{Original Article}
% Include section in journal if known, otherwise delete
  \paperfield{Global Change Biology}

\usepackage{lineno} % add
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}

\usepackage{graphicx}
\usepackage{booktabs} % book-quality tables
%%%%%%%%%%%%%%%% end my additions to header

\usepackage[T1]{fontenc}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \usepackage{fontspec}
  \ifxetex
    \usepackage{xltxtra,xunicode}
  \fi
  \defaultfontfeatures{Mapping=tex-text,Scale=MatchLowercase}
  \newcommand{\euro}{€}
\fi
% use microtype if available
\IfFileExists{microtype.sty}{\usepackage{microtype}}{}
\bibliographystyle{elsarticle-harv}
\usepackage{longtable}
\ifxetex
  \usepackage[setpagesize=false, % page size defined by xetex
              unicode=false, % unicode breaks when used with xetex
              xetex]{hyperref}
\else
  \usepackage[unicode=true]{hyperref}
\fi
\hypersetup{breaklinks=true,
            bookmarks=true,
            pdfauthor={},
            pdftitle={Electrochemical Properties of Peat Particulate Organic Matter on a Global Scale: Relation to Peat Chemistry and Degree of Decomposition},
            colorlinks=false,
            urlcolor=blue,
            linkcolor=magenta,
            pdfborder={0 0 0}}
\urlstyle{same}  % don't use monospace font for urls

\setcounter{secnumdepth}{5}
% Pandoc toggle for numbering sections (defaults to be off)

% Pandoc citation processing

% Pandoc header
\usepackage[backend=biber, style=authoryear]{biblatex}
\bibliography{references.bib}
\usepackage{setspace}

\DeclareSIQualifier\carbon{C}
\DeclareSIQualifier\sample{sample}
\sisetup{
	qualifier-mode = subscript
	}
\DeclareSIUnit\wn{\cm\tothe{-1}}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}



\begin{document}

\title{Electrochemical Properties of Peat Particulate Organic Matter on a Global Scale: Relation to Peat Chemistry and Degree of Decomposition}

% List abbreviations here, if any. Please note that it is preferred that abbreviations be defined at the first instance they appear in the text, rather than creating an abbreviations list.

% Include full author names and degrees, when required by the journal.
% Use the \authfn to add symbols for additional footnotes and present addresses, if any. Usually start with 1 for notes about author contributions; then continuing with 2 etc if any author has a different present address.

\author[1]{Henning Teickner }
%  \ead{\href{mailto:henning.teickner@uni-muenster.de}{\nolinkurl{henning.teickner@uni-muenster.de}}}  % --- todo: check if this can be added later
\author[1, 2]{Chuanyu Gao \authfn{1}}
%  % --- todo: check if this can be added later
\author[1]{Klaus-Holger Knorr }
%  % --- todo: check if this can be added later
\affil[1]{ILÖK, Ecohydrology and Biogeochemistry Group, University of Münster, Heisenbergstr. 2, 48149 Münster, Germany}
\affil[2]{Key Laboratory of Wetland Ecology and Environment, Northeast Institute of Geography and Agroecology, Chinese Academy of Sciences, Shengbei Street 4888, 130102, Changchun, China}
\contrib[\authfn{1}]{Co-corresponding author. Email: \href{mailto:gaochuanyu@iga.ac.cn}{\nolinkurl{gaochuanyu@iga.ac.cn}}}

\corraddress{Klaus-Holger Knorr, ILÖK, Ecohydrology and Biogeochemistry Group, University of Münster, Heisenbergstr. 2, 48149 Münster, Germany}
\corremail{\href{mailto:klaus-holger.knorr@uni-muenster.de}{\nolinkurl{klaus-holger.knorr@uni-muenster.de}}}

% \presentadd[\authfn{2}]{Department, Institution, City, State or Province, Postal Code, Country} % commented out since it is unclear how to handle this in the Rmd template

\fundinginfo{This Study was funded by the Deutsche Forschungsgemeinschaft (DFG, German Research Foundation) grant no. KN 929/12-1 to Klaus-Holger Knorr; Chuanyu Gao were supported by the Youth Innovation Promotion Association CAS (No.~2020235).}

% Include the name of the author that should appear in the running header
\runningauthor{Teickner et al.}

\begin{frontmatter}
\maketitle

\begin{abstract}
Peatlands are among the most relevant natural sources of methane. Methane formation in peatlands is controlled by the availability of electron acceptors for microbial respiration, including peat dissolved (DOM) and particulate organic matter (POM). These electrochemical properties are determined by peat chemistry and decomposition changes both. Peatland decomposition patterns probably are affected by climate change and permafrost thaw. Understanding peat electrochemical properties and its interactions is therefore crucial to understand current and future global methane formation.

Despite the much larger mass of POM in peat, knowledge on the ranges of its electron transfer capacities (electron accepting capacity -- EAC, and electron donating capacity -- EDC) is scarce in comparison to DOM and humic substances (HS). Moreover, it is unclear how peat POM chemistry relates to its EAC/EDC and how decomposition changes both.

To answer these questions, we compiled samples from 15 mid to high latitude peatlands across the world, quantified their EAC\(_\text{POM}\) and EDC\(_\text{POM}\), element ratios, decomposition indicators, and relative amounts of molecular structures as derived from mid infrared spectra, and conducted explorative and regression analyses.

Peat EAC\(_\text{POM}\) and EDC\(_\text{POM}\) are smaller than EAC and EDC of DOM and HS and are highly variable within and between sites. Both are small in highly decomposed peat (more lipids and aromatic backbone structures), unless there is a large amount of quinones and phenols (more carbonyls). Element ratio-based models failed to predict EAC\(_\text{POM}\) and EDC\(_\text{POM}\), but MIRS-based models probably can predict peat EAC\(_\text{POM}\), but not EDC\(_\text{POM}\).

To explain the observed patterns, we hypothesize a conceptual model that describes how vegetation chemistry and decomposition control polymeric phenol and quinone contents as drivers of peat electrochemical properties.

We suggest that considering these interactions or spatially resolved measurements of electrochemical properties are necessary to predict the impact of redox processes on global peatland methane formation.

% Please include a maximum of seven keywords
 \keywords{peat chemistry, electron accepting capacity, electron donating capacity, particulate organic matter, decomposition, mid infrared spectroscopy, electrochemical properties}
\end{abstract}
\end{frontmatter}





\begin{refsection}
%\doublespacing

\hypertarget{introduction}{%
\section{Introduction}\label{introduction}}

Mid to high-latitude peatlands are important actors in the global carbon cycle with differential effects on the global climate \autocite{Frolking.2011}. On the one side, they accumulated large amounts of atmospheric carbon dioxide (CO\(_2\)) in the form of peat \autocite{Limpens.2008}, on the other side they are sources of methane (CH\(_4\)) emissions to the atmosphere \autocite{Limpens.2008,Frolking.2011}.\\
Methane has 28 to 34 times the 100-year global warming potential of CO\(_2\) and therefore may be an important driver of climate warming \autocite{Myhre.2013}. Methane emissions from peatlands increase with higher water table depths, larger temperatures, and increased availability of labile organic matter (OM) \autocite{Moore.1989,Yavitt.1997,Limpens.2008}. Even though net C balances of global peatlands may be positive in the nearer future \autocite{Chaudhary.2020}, permafrost thaw and peat subsidence under warmer temperatures may favor such conditions and hence large CH\(_4\) emissions \autocite{Anisimov.2007,Koven.2011,Frolking.2011}. For this reason, it is important to refine our understanding of controls on CH\(_4\) formation in peatlands.\\
Methane formation is an obligatory anaerobic process and thus occurs only in the (at least temporally) anoxic zone of peatlands \autocite{Limpens.2008}. It can be suppressed if thermodynamically more favorable terminal electron acceptors (TEA), such as nitrate, iron oxides, sulfate, or organic molecules, are available \autocite{Blodau.2011,Klupfel.2014,Gao.2019}. Albeit inorganic TEAs typically have a comparatively small abundance in peatlands, suppression of CH\(_4\) formation can occur due to the large abundance of organic matter (OM) that acts as TEA \autocite{Gao.2019} and can be ``recharged'' even during short oxic periods \autocite{Klupfel.2014,Lau.2016,Walpen.2018b}. Whereas dissolved organic matter (DOM) acts as electron mediator during such respiration processes \autocite{Lau.2016,Gao.2019}, particulate organic matter (POM) provides the main part of the EAC of peat and can continuously reoxidize DOM mediators and other TEAs \autocite{Gao.2019,Blodau.2007}. Consequently, understanding the electrochemical properties of peat POM and how these are driven by vegetation chemistry and decomposition are key to understand CH\(_4\) emissions from peatlands.\\
How OM chemistry controls its capacity to accept electrons (electron accepting capacity, EAC) or donate electrons (electron donating capacity, EDC) has been analyzed mainly for DOM \autocite{Ratasuk.2007,Aeschbacher.2010,Aeschbacher.2012,Fimmen.2007,HernandezMontoya.2012,Tan.2017,Walpen.2018,LaCroix.2020}. The positive relation of the EAC to the C:H ratio and the EAC and EDC to indicators for aromaticity have been attributed to quinones and phenols representing the main contributors to the EAC and EDC, respectively \autocite{Aeschbacher.2010,Tan.2017}. In addition, sulfur and nitrogen containing functional groups can contribute to the EAC and EDC \autocite{Fimmen.2007,Ratasuk.2007,HernandezMontoya.2012} and the specific configuration of substituents and the degree of condensation control the magnitude and reversibility of the redox reactions \autocite{Ratasuk.2007,Uchimiya.2009}. Overall, there is a quite detailed conceptual understanding, which molecular structures are related to the EAC and EDC of HS and DOM.\\
In contrast, knowledge on peat POM EAC and EDC (EAC\(_\text{POM}\) and EDC\(_\text{POM}\)) and even more on how peat POM chemistry relates to its EAC and EDC is still scarce. Few studies analyzed the EAC and EDC of POM \autocite{Keller.2013,Lau.2015,Lau.2016,Gao.2019}. These studies focused on quantifying and analyzing the reversibility of the electron transfer, but not how POM chemistry relates to its electrochemical properties \autocite{Keller.2013,Lau.2015,Lau.2016,Gao.2019}. However, the ranges of the EAC\(_\text{POM}\) and EDC\(_\text{POM}\) for peat POM are not sufficiently quantified yet. Furthermore, since POM has different chemical properties than DOM \autocite{Worrall.2017}, it is unclear if POM electrochemical properties correlate in the same way to element ratios or molecular structures as for DOM.\\
``Classical'' indicators of peat chemistry, such as element ratios and the nominal oxidation state of carbon (C\(_\text{OX}\)), tools such as van-Krevelen diagrams to interpret contribution of different OM fractions, e.g.~lignin or polysaccharides \autocite{Kim.2003}, and mid infrared spectroscopy are promising techniques to explore how peat POM chemistry relates to its EAC and EDC. These methods have been widely used to analyze peat chemistry and to analyze electrochemical properties of DOM and HS \autocite{Worrall.2017,Leifeld.2012,Bader.2018,Moore.2018,Leifeld.2020,Cocozza.2003,Artz.2008,Hodgkins.2018,Tfaily.2014,Aeschbacher.2010,Aeschbacher.2012,Tan.2017,Lv.2018,LaCroix.2020}. This would enable linking information on different OM fractions and knowledge about assignments of molecular structures to mid infrared variables with the EAC and EDC.\\
Similarly unexplored are the relations between the degree of decomposition of peat and its EAC and EDC. Since decomposition can considerably transform peat POM and its molecular structures \autocite{Cocozza.2003}, it can have large effects on its EAC and EDC. Developing a conceptual understanding of these relations is therefore important to understand the mechanics of EAC and EDC changes during decomposition. Indicators of peat chemistry, e.g.~the N:C ratio (alternatively C:N) \autocite{Biester.2014}, C\(_\text{OX}\), and MIRS-derived humification indices \autocite{Broder.2012} have been widely used to analyze the degree of decomposition of peat \autocite{Biester.2014,Drollinger.2020}.\\
A practically useful product of such investigations may be the development of regression models to predict peat EAC and EDC from such indicators of peat chemistry or MIRS. For HS, a close relation between the EAC and H:C ratio was found \autocite{Aeschbacher.2010,Tan.2017}. MIRS has not been used for the prediction of electrochemical properties of OM, but has proven useful for its qualitative analysis \autocite{HernandezMontoya.2012,Yuan.2018} and the prediction of other peat properties \autocite{Hodgkins.2018,Artz.2008}.
On the one side, such regression models may enable to infer the EAC and EDC of peat samples of existing data, on the other side, they may serve at least as qualitative and (particularly for MIRS-based models) fast and cost effective screening tools which could assist in mapping peat EAC and EDC.\\
To synthesize, knowledge on the relation of peat EAC and EDC to its chemical properties and degree of decomposition is scarce. We thus were interested in investigating how peat chemistry relates to its EAC and EDC, and how decomposition may change both. Moreover, we wanted to assess if peat EAC and EDC may be predicted from simple indicators of peat chemistry or MIRS.
To this end, we aimed to (1) quantify the EAC\(_\text{POM}\) and EDC\(_\text{POM}\) of peat material formed under various environmental conditions and with a range of degrees of decomposition under standardized conditions, (2) analyze the relation of the EAC\(_\text{POM}\) and EDC\(_\text{POM}\) to bulk chemical properties, indicators for decomposition, and molecular structures, and (3) evaluate if element ratios (H:C, O:C, N:C, S:C) and MIRS can be used to predict peat EAC\(_\text{POM}\) and EDC\(_\text{POM}\), all based on a global data set of peat materials.\\
These analyses represent a basis for the conceptual understanding of how peat chemistry and decomposition affect the EAC and EDC. This knowledge can help understanding, quantifying, and predicting spatiotemporal variability in peat EAC and EDC and thus contribute to the quantitative understanding of peatland decomposition processes and CH\(_4\) formation on a global scale. With this, we aim to contribute information to better understand and predict peatland-climate interactions.

\hypertarget{materials-and-methods}{%
\section{Materials and methods}\label{materials-and-methods}}

To answer our main research question --- how peat chemistry relates to its EAC and EDC, and how decomposition may change both --- we compiled peat material and data for peatland sites with a broad range of climate regimes, dominant vegetation, and peatland types and performed various measurements under standardized conditions to describe their chemical and electrochemical characteristics. With this data, we conducted an explorative analysis, computed regression models that predict the EAC\textsubscript{POM} and EDC\textsubscript{POM} from element ratios or MIRS, and finally developed a conceptual model how initial peat chemistry and decomposition change chemical characteristics and the EAC\textsubscript{POM} and EDC\textsubscript{POM} of peat.\\
Laboratory analyses comprised in particular measurements of the EAC and EDC of peat oxidized with atmospheric oxygen prior the analyses under standardized conditions using mediated electrochemical reduction and oxidation (MER/MEO), respectively \autocite{Aeschbacher.2010,Lau.2015}. From this, the EAC\textsubscript{POM} and EDC\textsubscript{POM} was computed by subtracting the contribution of iron as determined by acid extraction.
Element contents were measured via elemental analysis and element ratios and the nominal oxidation state of carbon (C\(_\text{OX}\)) were computed thereof \autocite{Masiello.2008,Worrall.2017}. Molecular structures and information on the degree of decomposition were derived from MIRS. Different exploratory methods and regression models were used to analyze relations between variables and evaluate if element ratios or MIRS can be used to predict peat EAC and EDC.\\
Key limitations are the following: First, it is difficult to determine the exact contribution of solid iron to the EAC and EDC and therefore the calculated EAC\textsubscript{POM} and EDC\textsubscript{POM} values probably are biased proportionally to their iron content \autocite{Lau.2015}.
Second, since our study is not experimental, we could not control environmental conditions during peat formation that affect peat chemistry. Moreover, we could not obtain palaeovegetation data for all samples which would have been useful to constrain uncertainties about the effect of vegetation chemistry. Finally, our measurements probably are not representative for \emph{in situ} conditions due to standardized initial redox states, particle sizes, pH values, and redox potentials during measurements.\\
Despite these limitations, we could provide a detailed analysis how peat chemistry and degree of decomposition relate to its EAC\textsubscript{POM} and EDC\textsubscript{POM} and develop a conceptual model that can be experimentally tested in future studies. This was possible due to existing knowledge on peat chemistry, attempts to correct the bias of iron on EAC and EDC measurements, and careful interpretation of models while considering the effects of the analytical bias. In addition, information on palaeovegetation for some of the sites could be obtained from the literaure. Even though our analytical setup does not represent \emph{in situ} conditions, standardized conditions are mandatory to make peat properties comparable and are helpful to conceptually understand how peat chemistry and decomposition affect the EAC\textsubscript{POM} and EDC\textsubscript{POM}. In particular, all samples were measured in an oxidized state we assume to represent a standardized potential EAC\textsubscript{POM} and EDC\textsubscript{POM} of the materials under study.

\hypertarget{study-sites}{%
\subsection{Study sites}\label{study-sites}}

We compiled peat cores collected in the course of different projects from 15 peatland sites (one core per site). The different peatland sites are spread across the range of mid to high-latitude peatland areas (figure \ref{fig:study-sites-map-out}), experience different climatic regimes, and comprise both bogs and fens with different dominant vegetation cover (table \ref{tab:t-study-sites}). This enabled us to analyze peat material with a representative range of chemical properties and EAC and EDC.\\
Peat samples were selected from four approximate depth levels, depending on the vertical resolution of the peat cores and the maximum depth reached during coring (10 to 20, 30 to 40, 60 to 70 cm, and the deepest available sample per core at depths of 140 to 320 cm). We assumed that the samples cover most of the decomposition and vegetation-shift related variability in peat chemistry and hence EAC and EDC.

\begin{figure}[H]

{\centering \includegraphics[width=0.6\textwidth]{001-paper-main_files/figure-latex/study-sites-map-out-1}

}

\caption{Map of the peatland sites from which peat material and data were compiled for this study. The map was created using data from the R package rnaturalearth \autocite{South.2017}.}\label{fig:study-sites-map-out}
\end{figure}












\begin{landscape}\begin{table}

\caption{\label{tab:t-study-sites}Overview on the sites from which peat samples and data were derived from. Longitude and latitude are given in decimal degree North and East, respectively, the altitude is given in meter above sea level, peatland type differentiates between bogs and fens following available studies for the respective sites or from own investigations following concepts in \textcite{Rydin.2013}. "Temperature" is the mean annual temperature [$^{\circ}$C], "Precipitation" is the total annual precipitation [mm], and "References" are references with additional information on the sites. Elevation data were derived from the median values of the GMTED2010 data \autocite{Danielson.2011}. All climate data were derived from the WorldClim version 2.1 climate data for 1970-2000 (30 seconds spatial resolution, monthly temporal resolution) \autocite{Fick.2017}.}
\centering
\resizebox{\linewidth}{!}{
\begin{tabular}[t]{clcccc>{\raggedright\arraybackslash}p{4cm}cc>{\raggedright\arraybackslash}p{4cm}}
\toprule
Site label & Site name & Longitude & Latitude & Altitude & Peatland Type & Current vegetation & Temperature & Precipitation & References\\
\midrule
BB & Beerberg & 10.74 & 50.66 & 977 & Bog & \emph{Sphagnum}, shrubs & 5.3 & 1349 & \\
MK & Martinskapelle & 8.15 & 46.10 & 2089 & Bog & Shrubs, \emph{Sphagnum} & 2.1 & 1027 & \\
LT & La Tenine & 6.93 & 48.04 & 863 & Bog & \emph{Sphagnum}, shrubs & 6.4 & 1330 & \\
DE & Degerö & 19.56 & 64.18 & 275 & Fen & \emph{Sphagnum}, sedges, shrubs & 1.7 & 621 & \textcite{Sagerfors.2008}\\
ISH & Ishimbaevskoye & 65.34 & 57.47 & 77 & Fen & Shrubs, \emph{Sphagnum} & 1.5 & 472 & \textcite{Wertebach.2016}\\
\addlinespace
KR & Kyzyltun Ryam & 69.62 & 56.26 & 110 & Bog & \emph{Sphagnum} & 1.0 & 384 & \textcite{Larina.2013}\\
TX & Touxi & 127.84 & 42.28 & 1070 & Fen & Vascular plants, \emph{Sphagnum} & 1.3 & 754 & \\
DT & Dongtu & 127.86 & 42.27 & 1268 & Fen & Vascular plants, \emph{Sphagnum} & 0.6 & 775 & \\
LB & Lutose Bog & -117.17 & 59.48 & 309 & Bog & \emph{Sphagnum}, shrubs & -1.8 & 356 & \textcite{Heffernan.2020}\\
LP & Lutose Plateau & -117.17 & 59.48 & 309 & Bog & \emph{Sphagnum}, lichens & -1.8 & 356 & \textcite{Heffernan.2020}\\
\addlinespace
MB & Mer Bleue & -75.52 & 45.41 & 68 & Bog & Shrubs, \emph{Sphagnum} & 5.6 & 945 & \textcite{Elliott.2012}\\
PBR & P. Brunswick & -70.97 & -53.64 & 50 & Bog & \emph{Sphagnum}, shrubs & 6.0 & 797 & \textcite{Broder.2012}\\
SKY I-1 & Skyring I-1 & -72.45 & -52.14 & 75 & Bog & Vascular plants (\emph{Astelia pumila}), \emph{Sphagnum} & 6.1 & 637 & \textcite{Mathijssen.2019}\\
SKY I-6 & Skyring I-6 & -72.45 & -52.14 & 75 & Bog & \emph{Sphagnum} & 6.1 & 637 & \textcite{Mathijssen.2019}\\
SKY II & Skyring II & -72.13 & -52.51 & 36 & Bog & \emph{Sphagnum} & 6.3 & 690 & \textcite{Broder.2012}\\
\bottomrule
\end{tabular}}
\end{table}
\end{landscape}

\hypertarget{eac-and-edc-measurements}{%
\subsection{EAC and EDC measurements}\label{eac-and-edc-measurements}}

We measured the EAC and EDC of the peat samples using mediated electrochemical reduction (MER) and oxidation (MEO), respectively, following largely the protocols provided by \textcite{Lau.2015} and \textcite{Gao.2019}.\\
For this, the peat material was freeze dried (alpha 1-4 plus, Christ, Osterode, Germany) and finely ground to powder in a vibratory cup mill (tungsten carbide cups; Retsch MM 400, Haan, Germany). The ground samples were suspended in water in order to create a suspension that can be pipetted for analyses as described elsewhere \autocite{Lau.2015}. For this, approximately \(\SI{0.08}{\g}\) of sample and \(\SI{30}{\milli\L}\) of deionized, degassed, and anoxic water were used, or in case of lower amounts of sample available a similar ratio of water to solids.\\
The suspensions were transferred into a glove box with N\(_2\) atmosphere (\(<\SI{1}{ppm}\) O\(_2\); Inert Lab Glovebox, Innovative Technology, Amesbury, MA, USA) to perform the electrochemical measurements. For each measurement, an aliquot of each suspension, depending on the total organic carbon content and the expected range of the EAC/EDC (typically \(\SI{100}{\micro\L}\) suspension containing \(\SI[separate-uncertainty=true, multi-part-units = single]{0.2 \pm 0.01}{\milli\g}\)), was transferred into electrochemical cells. The suspensions were continuously stirred (topolino, IKA, Staufen, Germany) to ensure reproducible transfer into the electrochemical cells.\\
The electrochemcial cells and analytical setup consisted of a multichannel potentiostat (CH1000, CH Instruments, Austin, TX, USA), glassy carbon working electrodes (Sigradur, HTW, Thierhaupten, Germany), platinum counter electrodes (coiled \(\SI{0.4}{\milli\m}\) platinum wire, Sigma-Aldrich, St.~Louis, USA), and Ag/AgCl reference electrodes (RE-1B, ALS Co.~Ltd, Tokyo, Japan). All potentials were experimentally measured against Ag/AgCl reference, but are reported versus the standard hydrogen electrode.\\
The working electrode solution contained KCl as a background electrolyte (\(\SI{0.1}{\mol\per\L}\)) and was buffered to pH 7 (\(\SI{0.2}{\mol\per\L}\) KH\(_2\)PO\(_4\)) to ensure stable pH during measurements \autocite{Aeschbacher.2011} and to enable direct comparisons with available data \autocite{Aeschbacher.2010,Walpen.2018,Tan.2017}. Prior to analyses of samples \(\SI{180}{\micro\L}\) of a \SI{0.1}{\Molar} solution of the mediator diquat (6,7--dihydrodipyrido {[}1,2--a:20,10--c{]} pyraziniumdibromid monohydrate; EH\(_0=\SI{-0.36}{\V}\); Supelco, USA; 95\% purity) was added for MER, and a similar amount of ABTS (2,2--azino--bis-(3--ethylbenzthiazoline--6--sulfonic acid) ammonium salt; EH\(_0=\SI{+0.68}{\V}\); Sigma Aldrich, St.~Louis, USA; 98\% purity) for MEO.\\
Values of EAC and EDC were determined in MER and MEO, respectively, by integrating the reductive or oxidative current signals over time and normalizing the quantified numbers of electrons transferred to the amount of carbon added for analysis \autocite{Aeschbacher.2010}. The sum of EAC and EDC is referred to as total electron exchange capacity (EEC\textsubscript{tot}).\\
Strictly, the obtained EAC and EDC values are the combined EAC and EDC of the POM, DOM, and dissolved inorganic ions and inorganic particles that could be reduced and oxidized, respectively. Prior studies of organic rich sediments and peat samples suggest that dissolved inorganic ions and DOM have a negligible contribution to the EAC and EDC of bulk peat material (\textasciitilde1\%) \autocite{Lau.2015,Gao.2019} and therefore we assume that our measurements are representative for the solid phase.\\
Even though POM is assumed to be the dominant contributor to the EAC and EDC of organic rich sediments such as peat \autocite{Lau.2015,Gao.2019}, solid iron phases can contribute to the EAC and EDC of peat as measured by MER/MEO \autocite{Lau.2015}. We therefore corrected the measured EAC and EDC values for contributions of Fe\(^{2+}\) (each mol contributing one mol electrons to the EDC) and Fe\(^{3+}\) (each mol contributing one mol electrons to the EAC) \autocite{Lau.2015,Gao.2019}. To this end, we extracted iron by adding \SI{4}{\milli\liter} \SI{1}{\Molar} HCl to \SI{1}{\milli\liter} of each sample (in some cases less material had to be used), letting the suspensions rest for \SI{72}{\hour} in the dark, and filtering the solution through \SI{0.22}{\micro\meter} Nylon syringe filters. Concentrations of Fe\(^{2+}\) and Fe\(^{3+}\) in the filtrate were measured spectrophotometrically using the 1,10--phenanthroline method \autocite{Tamura.1974} and from this, we computed the contributions of iron to the EAC (EAC\textsubscript{Fe$^{3+}$}) and EDC (EDC\textsubscript{Fe$^{2+}$}), respectively. The EAC\textsubscript{POM} was then computed by subtracting EAC\textsubscript{Fe$^{3+}$} from the measured EAC and the EDC\textsubscript{POM} by subtracting EDC\textsubscript{Fe$^{2+}$} from the measured EDC \autocite{Lau.2015}.\\
There are several known issues with this procedure. First, acid extraction may not extract all redox active iron moieties \autocite{Lau.2016}. Second, different iron minerals have different redox dynamics \autocite{Aeppli.2018}. Third, during acid extraction, the redox equilibrium between iron and OM is shifted and Fe\(^{3+}\) is reduced to Fe\(^{2+}\) \autocite{Lau.2015}. Consequently, the contribution of iron to the EDC is typically overestimated, whereas the contribution of iron to the EAC is typically underestimated \autocite{Lau.2015}.\\
The first two issues may be negligible for most samples because peat typically contains few mineral particles and hence most iron typically is acid extractable (supporting figure \ref{fig:p-fe-xrf-comparison-res}). However, we cannot fully exclude that more iron moieties than that accessible via acid extraction contributed to the EAC and EDC for samples with larger iron contents (supporting figure \ref{fig:p-fe-xrf-comparison-res}). The third issue probably affected our calculated EAC\textsubscript{POM} and EDC\textsubscript{POM} values. One indication for this is that 5 EDC\textsubscript{POM} values were negative (minimum: \SI{-8}{\micro\mol\per\gram\carbon}). We therefore assume that the calculated EAC\textsubscript{POM} and EDC\textsubscript{POM} values are biased for samples with high iron content and considered this during data analysis and interpretation.\\
We finally report the EAC\textsubscript{POM} and EDC\textsubscript{POM} relative to the C mass of the measured sample (mass of C in the POM suspension aliquot). Moreover, we computed the EAC\textsubscript{POM} and EDC\textsubscript{POM} relative to the total mass of the sample for comparison with values reported in other studies. For each sample, we computed average EAC\textsubscript{POM} and EDC\textsubscript{POM} values and respective standard deviations from the replicate measurements. During this, we discarded one EAC replicate measurement for which we assumed measurement errors because it differed extremely (more than \(\SI{1000}{\micro\mol\per\gram\carbon}\)) from the remaining replicate measurements for the same sample (supplementary figure \ref{fig:el-preprocessing-p1-res}).

\hypertarget{element-contents}{%
\subsection{Element contents}\label{element-contents}}

We analyzed concentrations of C, N, and S for all samples by catalytic combustion using an elemental analyzer (EA 3000, Eurovector, Pavia, Italy) . Concentrations of H and O were determined based on the modified Dumas Method, using an CHNS/O analyzer (FlashEA 1112, Thermo Fisher Scientific, Delft, The Netherlands). The nominal oxidation state of C (C\(_\textrm{ox}\)) was computed from the contents of C, H, N, and O \autocite{Masiello.2008,Worrall.2016b}.\\
Total concentrations of other elements (Fe, P and others; see supporting table \ref{tab:t-cor-el-xrf} for a full list of measured elements) were determined by wavelength dispersive X-ray fluorescence spectroscopy (WD-XRF; ZSX Primus II, Rigaku, Tokyo, Japan) calibrated with a set of 15 reference materials, consisting of certified plant, peat, and sediment materials, and 5 in-house working standards. Analyses were done on \(\SI{500}{\milli\g}\) of ground, powdered sample, pressed to a \(\SI{13}{\milli\m}\) pellet (without pelleting aids) at a load of approximately \SI{7}{\tonne}. For few samples, S contents were derived from the WD-XRF data.

\hypertarget{mid-infrared-spectroscopy}{%
\subsection{Mid infrared spectroscopy}\label{mid-infrared-spectroscopy}}

Fourier-transform mid infrared spectra (MIRS) were used to obtain detailed information on peat molecular structures and to compute regression models for the prediction of peat EAC and EDC. Two mg of powdered sample were mixed with 200 mg KBr (FTIR grade, Sigma Aldrich, St.~Louis, MO, USA) and pressed to a 13 mm pellet. Spectra were recorded on a Cary 660 FTIR spectrometer (Agilent, Santa Clara, CA, USA) in the range 650 to 4000 cm\(^{-1}\) at a resolution of 0.5 to \SI{2}{\wn}. A number of 32 scans per sample were collected in the absorbance mode and a KBr background was subtracted.\\
The recorded MIRS were preprocessed to remove known artifacts and harmonize the data. Spectral preprocessing was performed using the package ir (0.0.0.9000) \autocite{Teickner.2020}. All spectra were linearly interpolated to a resolution of 1 cm\(^{-1}\). To remove artifacts caused by CO\(_2\), all spectra were linearly interpolated in the region 2290 to 2400 cm\(^{-1}\). Subsequently, baseline correction was performed using a rubberband algorithm (based on a convex hull procedure combined with smoothing splines) \autocite{Beleites.2020}. After this, spectra were clipped by 20 and 10 wavenumber units at the start and end, to the range 810 to \SI{3990}{\wn}, and baseline correction was performed a second time to fully align the start and end points of the spectra. Finally, all spectra were normalized to unit intensity sum. To assess the degree of peat decomposition, we computed a humification index by dividing the intensity at \(\SI{1630}{\wn}\) and \(\SI{1090}{\wn}\) (denoted as HI\textsubscript{1630/1090}) \autocite{Broder.2012} using irpeat (0.0.0.9000) \autocite{Teickner.2020b}.\\
Two transformed versions of the spectra were created for the computation of MIRS-based regression models: The first is a binned version and the second is a derived and binned version of the preprocessed spectra. Binning was performed with a bin width of \SI{10}{\wn} to reduce autocorrelation and noise in the spectra. Prior to binning, the preprocessed spectra were derived using a Savitzgy-Golay filter (filter width: \SI{5}{\wn}) \autocite{signaldevelopers.2014}. Derivatization can improve the resolution of features and therefore can improve the predictive accuracy of regression models \autocite{Stuart.2005,Engel.2013}.

\hypertarget{statistical-analyses}{%
\subsection{Statistical analyses}\label{statistical-analyses}}

\hypertarget{balancing-the-analytical-bias-in-eac-and-edc-values}{%
\subsubsection{\texorpdfstring{Balancing the analytical bias in EAC\textsubscript{POM} and EDC\textsubscript{POM} values}{Balancing the analytical bias in EAC and EDC values}}\label{balancing-the-analytical-bias-in-eac-and-edc-values}}

As mentioned in the previous section, the EAC\textsubscript{POM} and EDC\textsubscript{POM} values computed from measured EAC and EDC values and acid extracted iron ion contents probably are biased, especially for samples with high iron content \autocite{Lau.2015,Lau.2016}. Since we are interested in electrochemical properties of POM, this bias must be considered during all data analysis steps. We aimed to do this first by quantifying the maximum potential contribution of iron to the EAC and EDC, second, by creating a filtered data set for each the EAC\textsubscript{POM} and EDC\textsubscript{POM} containing only data where the maximum potential contribution of iron to the EAC and EDC was \(\le\)\SI{100}{\micro\mol\per\gram\carbon}, respectively, and third, performing all analyses for the filtered data set.\\
The maximum potential contribution of iron to the EAC and EDC was determined as the total concentration of iron in the acid extract (sum of the concentrations of Fe\(^{2+}\) and Fe\(^{3+}\)). We assumed that non-extracted iron is redox inactive and hence this total iron concentration reflects the maximum potential contribution of iron to either the EAC or EDC, irrespective of the initial redox state and redox state changes during the acid extraction. This assumption is true for samples with low total iron contents, but cannot be validated for samples with larger iron contents (supporting figure \ref{fig:p-fe-xrf-comparison-res}) \autocite{Lau.2016}. An overview on the maximum potential contribution of iron to the EAC and EDC across all samples computed from the acid extractable iron content can be found in supplementary figure \ref{fig:p-fe-contribution-abs-res}. The threshold of \(\le\)\SI{100}{\micro\mol\per\gram\carbon} was chosen to balance the reduction in the analytical bias in the filtered data and the reduction in sample size, resulting in sample sizes of 52 for the EAC and EDC. As a result, there was only a constant offset bias between corrected and uncorrected values for the EAC and EDC (supporting figure \ref{fig:p-fe-corrected-uncorrected-res}).\\
We stress that typical measured EAC and EDC values often are much larger than \SI{100}{\micro\mol\per\gram\carbon} and that samples with large acid extracted (and total) iron contents typically have a small EAC and EDC (supporting figures \ref{fig:p-fe-raw-iron} and \ref{fig:p-fe-corrected-uncorrected-res}), suggesting that the maximum bias probably is low. Therefore it is unlikely that the remaining bias had a large influence on the results. As mentioned above, we cannot, however, fully exclude contributions of non-acid extractable iron minerals to the EAC and EDC. We also note that choosing a tighter filter threshold is likely to cause selection bias since samples with high acid extracted iron content tend to be more decomposed (supporting figure \ref{fig:p-fe-decomposition-res}).

\hypertarget{eac-and-edc-variability}{%
\subsubsection{\texorpdfstring{EAC\textsubscript{POM} and EDC\textsubscript{POM} variability}{EAC and EDC variability}}\label{eac-and-edc-variability}}

We created several plots and computed Pearson correlation coefficients to analyze patterns in the samples' EAC\textsubscript{POM} and EDC\textsubscript{POM}.
More specifically, we plotted depth profiles for each site to understand depth-related changes and to compare the overall EAC\textsubscript{POM} and EDC\textsubscript{POM} between different sites. Moreover, we created a histogram of the measured values for each the EAC\textsubscript{POM} and EDC\textsubscript{POM} and compared our values with those measured for various HS and DOM samples in other studies \autocite{Aeschbacher.2012,Tan.2017,Walpen.2018}. These values from other studies were extracted from the publications' figures using the R package digitize \autocite{Poisot.2011}. Finally, we plotted the EDC\textsubscript{POM} versus the EAC\textsubscript{POM} to analyze their relation (inspired by \textcite{Aeschbacher.2012}). We did not include analyses for the EEC\textsubscript{POM} (EAC\textsubscript{POM} + EDC\textsubscript{POM}) since the EEC\textsubscript{POM} is strongly related to the EAC\textsubscript{POM} (Pearson correlation \(=0.91\) and \(0.92\) for the filtered and unfiltered data, respectively).

\hypertarget{relation-to-bulk-chemical-properties-and-decomposition-indicators}{%
\subsubsection{Relation to Bulk Chemical Properties and Decomposition Indicators}\label{relation-to-bulk-chemical-properties-and-decomposition-indicators}}

To analyze the relation of the EAC\textsubscript{POM}, EDC\textsubscript{POM}, and EDC\textsubscript{POM}:EAC\textsubscript{POM} ratio to different indicators of bulk peat chemistry (H:C, O:C, N:C, S:C ratio, HI\(_\text{1630/1090}\), and C\(_\text{OX}\)), we created scatterplots and computed their pairwise Pearson correlation. The H:C ratio has been shown to relate negatively to the EAC and EDC of HS \autocite{Aeschbacher.2010,Tan.2017,Lv.2018}. The O:C, N:C, S:C ratio, and C\(_\text{OX}\) are indicators for peat decomposition \autocite{Masiello.2008,Biester.2014,Leifeld.2012} and C\(_\text{OX}\) was positively related to the EDC of HS \autocite{Lv.2018}. The O:C ratio is an indicator for the amount of polysaccharides \autocite{Kim.2003} which are not assumed to contribute to the EAC\textsubscript{POM} and EDC\textsubscript{POM}. There is some evidence for the contribution of nitrogen and sulfur containing functional groups to the EAC\textsubscript{POM} and EDC\textsubscript{POM} \autocite{Ratasuk.2007,Fimmen.2007,HernandezMontoya.2012} and the N:C, and S:C ratio might give information on this, too.\\
To qualitatively analyze potential joint effects of the H:C and O:C ratio and relate their variability to different OM fractions, we created van-Krevelen plots.
Van-Krevelen plots are commonly used to analyze properties of chemical formulas of individual compounds assigned based on mass spectrometry data by plotting the respective H:C ratio in relation to their O:C ratio \autocite{Kim.2003}. Different regions in van-Krevelen plots are assigned to different OM fractions based on their typical element ratios \autocite{Kim.2003}. Since our analyses refer to peat bulk samples and not individual compounds, we call them van-Krevelen-\emph{like}. Such plots are used to analyze changes in the relative amount of OM fractions in peat \autocite{Leifeld.2012,Bader.2018}. Scaling point sizes according to the EAC\textsubscript{POM} and EDC\textsubscript{POM} values allowed us to visually analyze patterns in these variables across the H:C-O:C gradient and to relate this to changes in the relative amount of different OM fractions.\\
For some International Humic Substances Society (IHSS) reference samples, information on element contents \autocite{HuffmanLaboratories.NA} and EAC and EDC \autocite{Aeschbacher.2012} are available. We therefore could include these samples in the van-Krevelen-like plots and compare if these fit into any gradient for our peat samples.

\hypertarget{regression-models}{%
\subsubsection{Regression Models}\label{regression-models}}

We used regression models to analyze if peat EAC\textsubscript{POM} and EDC\textsubscript{POM} can be predicted from a linear combination of individual element ratios (H:C, O:C, N:C, S:C).
Different regression approaches were investigated: (1) including only the H:C and O:C ratio, and (2) including all four element ratios. In addition, we evaluated if using robust regression (coefficients are assumed to follow a Student-t distribution instead of a Gaussian distribution) has an effect on the model fit since several samples did not fit in the overall pattern. We did not compute regression models with one element ratio alone as predictor variable because our explorative analysis indicated no strong pairwise correlation to any of the element ratios.\\
We used Bayesian hierarchical models to consider the uncertainties of the replicate measurements and that these were different for different samples (supplementary figure \ref{fig:p-reg-distogram-res} provides an overview on the model structure). For the EAC\textsubscript{POM} and EDC\textsubscript{POM} values (both individual measurements and replicate measurement averages) we assumed a Gamma distribution with log-link function since this is the maximum entropy distribution for a variable with values \(\ge0\) and a mean value. Individual replicate measurements with EDC\textsubscript{POM} values \(\le \SI{0}{\micro\mol\per\gram\carbon}\) were set to \SI{0}{\micro\mol\per\gram\carbon} for this. Since the absolute values of these measurements is small in comparison to the median EDC\textsubscript{POM} values, we assumed that this causes no bias in our analyses. Further details on the specification of the element ratio-based models can be found in the supporting information.\\
All regression models were developed and fitted with Stan \autocite{Carpenter.2017} via the R packages rstan (2.19.3) \autocite{StanDevelopmentTeam.2020} and using rstantools (2.0.0) \autocite{Gabry.2019b}. The model was fitted using Markov Chain Monte Carlo (MCMC) sampling. Four MCMC chains were run for 2000 iterations, including 500 warmup iterations (6000 post-warmup samples in total). Model validation was performed using the \(\hat{R}\) statistic, trace plots of the MCMC draws, posterior predictive checks, area plots of the estimate regression parameters \autocite{Gelman.2014b,Gabry.2019} (R package bayesplot (1.7.2) \autocite{Gabry.2019}), and residual analysis.

\hypertarget{relation-to-molecular-structures}{%
\subsubsection{Relation to Molecular Structures}\label{relation-to-molecular-structures}}

To analyze the relation of the EAC\textsubscript{POM} and EDC\textsubscript{POM} to peat molecular structures, we analyzed the collected MIRS by computing correlation spectra and regression models and by assigning selected spectral variables to molecular structures using literature references \autocite{Cocozza.2003,Stuart.2005,Kubo.2005,Schmidt.2006,Artz.2008}. Using this strategy, we could identify individually and jointly influential variables and analyze their relation to the EAC\textsubscript{POM} and EDC\textsubscript{POM}.\\
Computing regression models based on MIRS is typically problematic due to the large number of spectral variables in comparison to the number of samples which potentially causes overfitting. Widely used approaches to overcome this are partial least squares regression (PLSR) and regularization \autocites[e.g.~][]{Artz.2008}{Ferragina.2015}. Both approaches may differ in their predictive performance, depending on properties of the data \autocite{Ferragina.2015}. In addition, different preprocessing approaches for MIRS can affect the predictive performance of models \autocite{Engel.2013}. We therefore computed not only one regression model for each the EAC\textsubscript{POM} and EDC\textsubscript{POM}, but four, using either non-derived spectra or first derivative spectra as input data, and PLSR or Bayesian regularization, respectively.\\
A drawback of both PLSR and Bayesian regularization is that the resulting models often are not straightforward to interpret. PLSR compresses individual variables into factors that can be tedious to interpret and both approaches do not select individual variables for interpretation \autocite{Yun.2019,Piironen.2020}. Establishing direct links between molecular structures and the target variable (e.g.~the EAC\textsubscript{POM}) is therefore difficult.\\
We applied Bayesian projection \autocite{Piironen.2020} on all computed models to overcome these interpretation issues. Bayesian projection seeks to find a reduced model that is similar to the full model in terms of its posterior distribution within some defined tolerance threshold \autocite{Piironen.2020}. In contrast to other approaches, Bayesian projection has the advantages that it guards against overfitting and incorporates information of the complete posterior distribution of the full model \autocite{Piironen.2017,Piironen.2020}. Thus, Bayesian projection allowed us to focus on few influential mid infrared variables that produce a similar fit to the data as the reference model including all spectral variables. This allowed us to establish more direct links between the underlying molecular structures and the EAC\textsubscript{POM} and EDC\textsubscript{POM}.\\
PLSR models were computed using the R package pls (2.7-2) \autocite{Mevik.2019}. Regression models with Bayesian regularization were computed using rstan (2.19.3) \autocite{StanDevelopmentTeam.2020} and rstanarm (2.19.3) \autocite{Goodrich.2020}, and using a vague Gaussian prior for PLSR-based models and using a horseshoe prior with an assumed number of relevant variables set to 8 \autocite{Piironen.2017c} for Bayesian regularization models. Bayesian projection was performed using projpred (1.1.6) \autocite{Piironen.2019}. All regression models were fitted with the same MCMC parameters and validated as described above for the models based on element ratios. Further details on the projection approach are described in the supporting information.

\hypertarget{predictive-performance-of-the-regression-models}{%
\subsubsection{Predictive Performance of the Regression Models}\label{predictive-performance-of-the-regression-models}}

We also wanted to analyze if regression models using element ratios or mid infrared variables may be used to predict peat EAC\textsubscript{POM} and EDC\textsubscript{POM}. We therefore estimated the predictive performance of the regression models and compared them among each other and with the measurement error of the replicate measurements. We assessed the predictive performance of the models computed on the filtered data only to avoid predicting biased data and because both data sets yielded similar fits. We used the root mean square error (RMSE) as performance metric \autocite{Bellocchi.2010}.\\
The relative small data set impedes using an independent test data set to compute the predictive performance of the models for new data. For this reason, we used 10-fold cross-validation (CV) to validate the models \autocite{Roberts.2017}. Further details on the CV procedure can be found in the supporting information.\\
As we did not observe large deviations between alternative regression models, we cross-validated only the regression models containing all element ratios (H:C, O:C, N:C, S:C) and the MIRS-based models using Bayesian regularization and non-derived spectra.
The RMSE was computed between the MCMC draws for predictions of the regression models for new observations and MCMC draws for estimates of the samples' average EAC\textsubscript{POM} or EDC\textsubscript{POM}, respectively. This allowed us to consider the uncertainties of the repeated measurements during CV, and to compute a probability distribution of the RMSE values based on the CV uncertainty, as well as the models' uncertainties.

\hypertarget{software}{%
\subsection{Software}\label{software}}

All computations were preformed in R (4.0.1) \autocite{RCoreTeam.2020}. Graphics were created --- except otherwise stated --- using ggplot2 (3.3.2) \autocite{Wickham.2016}, cowplot (1.0.0) \autocite{Wilke.2019}, ggrepel (0.8.2) \autocite{Slowikowski.2020}, and ggforce (0.3.1) \autocite{Pedersen.2019}. Spatial data was handled using sf (0.9-3) \autocite{Pebesma.2018b}, sp (1.4-2) \autocite{Pebesma.2005}, rgeos (0.5-3) \autocite{Bivand.2020}, and raster (3.3-13) \autocite{Hijmans.2020}. dplyr (1.0.0) \autocite{Wickham.2020e}, purrr (0.3.4) \autocite{Henry.2020}, magrittr (1.5) \autocite{Bache.2014}, and tidyr (1.1.0) \autocite{Wickham.2020f} were used for general data processing. Measurement errors and units were handled with quantities (0.1.5) \autocite{Pebesma.2016,Ucar.2019}, and element content data with elco (0.0.0.9000) \autocite{Teickner.2020e}.

\hypertarget{results}{%
\section{Results}\label{results}}

\hypertarget{eac-and-edc}{%
\subsection{\texorpdfstring{EAC\textsubscript{POM} and EDC\textsubscript{POM}}{EAC and EDC}}\label{eac-and-edc}}

Our peat samples' average EAC\textsubscript{POM} ranges between 179 and \SI{1228}{\micro\mol\per\g\carbon} and their EDC\textsubscript{POM} between 9 and \SI{569}{\micro\mol\per\g\carbon} (after filtering; see table \ref{tab:t-ranges-sites} for site-specific values). The EAC\textsubscript{POM} is typically larger than the EDC\textsubscript{POM}, with few exceptions, and both are loosely positively related (\(\rho=\) 0.39), as shown in figure \ref{fig:p-el-eac-edc-res}.\\
The EAC\textsubscript{POM} and EDC\textsubscript{POM} vary considerably between different sites and the depth-related within-site variability is also large (figure \ref{fig:p-el-depth-profiles-res}). In addition, no general depth-related pattern is visible: For some peat cores, the uppermost sample had the largest EAC\textsubscript{POM} or EDC\textsubscript{POM}, for others the deepest, and for some the intermediate samples. The same figure also shows that the EAC\textsubscript{POM} and EDC\textsubscript{POM} can change independently or even inversely to each other along the peat profile. Finally, our specific sites did not show distinct patterns in their EAC\textsubscript{POM} and EDC\textsubscript{POM} to differentiate bogs and fens (supplementary figure \ref{fig:el-comparison-peatland-types-res}).\\
Figure \ref{fig:p-el-comparison-res} compares EAC\textsubscript{POM} and EDC\textsubscript{POM} for our peat samples to those for different HS and peat DOM samples obtained from different studies \autocite{Aeschbacher.2012,Tan.2017,Walpen.2018}. Most HS and peat DOM samples have a clearly larger EAC and EDC, whereby mineral soil HS \autocite{Tan.2017} seem to have intermediate values relative to our measurements on the one side and the larger values for various IHSS reference samples \autocite{Aeschbacher.2012} and peat DOM samples \autocite{Walpen.2018} on the other side.

\begin{landscape}\begin{table}

\caption{\label{tab:t-ranges-sites}Overview on the electrochemical and chemical properties and decomposition states of the peat samples for the different sites (mean, min, max). EAC\textsubscript{POM} and EDC\textsubscript{POM} are given in $\si{\micro\mol\per\g\carbon}$. Element ratios are molar ratios. C$_\text{OX}$ is the nominal oxidation state of carbon. HI$_\text{1630/1090}$ is the ratio of the intensities at 1630 and $\SI{1090}{\wn}$ computed from mid infrared spectra.}
\centering
\resizebox{\linewidth}{!}{
\begin{tabular}[t]{lcccccccl}
\toprule
Site label & EAC$_\text{POM}$ & EDC$_\text{POM}$ & H:C & O:C & N:C & S:C & C$_\text{OX}$ & HI$_\text{1630/1090}$\\
\midrule
BB & 477 (390, 534) & 397 (327, 463) & 1.46 (1.4, 1.5) & 0.68 (0.62, 0.74) & 0.01 (0.01, 0.02) & 0.001 (0, 0.003) & -0.07 (-0.12, 0.02) & 0.56 (0.44, 0.62)\\
MK & 581 (339, 940) & 341 (213, 492) & 1.44 (1.43, 1.45) & 0.61 (0.52, 0.69) & 0.02 (0.01, 0.03) & 0.001 (0, 0.001) & -0.16 (-0.29, -0.01) & 0.72 (0.55, 0.86)\\
LT & 542 (427, 734) & 310 (161, 452) & 1.49 (1.48, 1.52) & 0.68 (0.66, 0.7) & 0.01 (0.01, 0.02) & 0.001 (0, 0.001) & -0.1 (-0.13, -0.05) & 0.58 (0.5, 0.63)\\
DE & 477 (424, 590) & 466 (288, 673) & 1.55 (1.49, 1.61) & 0.66 (0.6, 0.7) & 0.02 (0.01, 0.02) & 0 (0, 0.001) & -0.18 (-0.25, -0.08) & 0.54 (0.49, 0.59)\\
ISH & 633 (435, 926) & 227 (176, 349) & 1.42 (1.35, 1.48) & 0.57 (0.54, 0.61) & 0.02 (0.02, 0.03) & 0.001 (0.001, 0.003) & -0.22 (-0.28, -0.13) & 0.93 (0.66, 1.1)\\
\addlinespace
KR & 721 (486, 907) & 402 (276, 548) & 1.5 (1.39, 1.56) & 0.65 (0.59, 0.69) & 0.02 (0.01, 0.02) & 0.001 (0.001, 0.001) & -0.16 (-0.25, -0.09) & 0.75 (0.64, 1.01)\\
TX & 415 (302, 636) & 80 (36, 128) & 1.51 (1.47, 1.56) & 0.56 (0.53, 0.61) & 0.04 (0.04, 0.05) & 0.002 (0.001, 0.002) & -0.27 (-0.31, -0.2) & 0.83 (0.61, 0.98)\\
DT & 325 (255, 388) & 121 (98, 140) & 1.47 (1.4, 1.53) & 0.5 (0.48, 0.53) & 0.04 (0.04, 0.05) & 0.002 (0.001, 0.002) & -0.33 (-0.38, -0.31) & 0.89 (0.8, 0.99)\\
LB & 642 (324, 1208) & 363 (284, 410) & 1.48 (1.29, 1.63) & 0.68 (0.57, 0.73) & 0.02 (0.01, 0.02) & 0.001 (0, 0.002) & -0.06 (-0.13, -0.01) & 0.45 (0.37, 0.62)\\
LP & 968 (691, 1228) & 269 (207, 334) & 1.4 (1.28, 1.54) & 0.65 (0.6, 0.7) & 0.02 (0.01, 0.02) & 0.001 (0, 0.001) & -0.04 (-0.08, 0) & 0.61 (0.55, 0.66)\\
\addlinespace
MB & 758 (656, 868) & 351 (247, 569) & 1.41 (1.31, 1.46) & 0.64 (0.52, 0.72) & 0.02 (0.01, 0.03) & 0.001 (0, 0.001) & -0.09 (-0.21, 0.05) & 0.69 (0.47, 0.95)\\
PBR & 799 (455, 1192) & 461 (376, 541) & 1.38 (1.3, 1.45) & 0.6 (0.56, 0.65) & 0.02 (0.01, 0.02) & 0.001 (0.001, 0.001) & -0.12 (-0.15, -0.11) & 0.83 (0.7, 0.95)\\
SKY I-1 & 323 (179, 468) & 76 (10, 155) & 1.43 (1.38, 1.51) & 0.58 (0.55, 0.63) & 0.03 (0.02, 0.04) & 0 (0, 0.001) & -0.2 (-0.29, -0.07) & 0.9 (0.54, 1.13)\\
SKY I-6 & 346 (234, 497) & 169 (58, 269) & 1.44 (1.4, 1.48) & 0.55 (0.48, 0.62) & 0.02 (0.02, 0.02) & 0 (0, 0.001) & -0.28 (-0.38, -0.14) & 0.92 (0.65, 1.37)\\
SKY II & 749 (570, 912) & 376 (347, 403) & 1.46 (1.44, 1.48) & 0.67 (0.53, 0.74) & 0.01 (0.01, 0.02) & 0 (0, 0.001) & -0.07 (-0.32, 0.08) & 0.58 (0.44, 0.73)\\
\bottomrule
\end{tabular}}
\end{table}
\end{landscape}

\begin{figure}[H]

{\centering \includegraphics[width=0.5\textwidth]{001-paper-main_files/figure-latex/p-el-eac-edc-res-1}

}

\caption{Plot of the average EAC\textsubscript{POM} versus the average EDC\textsubscript{POM}. Error bars represent the respective standard errors from replicate measurements. Samples below the diagonal line have a larger EAC\textsubscript{POM} than EDC\textsubscript{POM}. Only samples with a potential contribution of iron to the EAC and EDC $\le\SI{100}{\micro\mol\per\gram\carbon}$ are shown.}\label{fig:p-el-eac-edc-res}
\end{figure}

\begin{figure}[H]

{\centering \includegraphics[width=0.35\textwidth]{001-paper-main_files/figure-latex/p-el-depth-profiles-res-1}

}

\caption{Depth profiles of the EAC\textsubscript{POM} and EDC\textsubscript{POM} for each peat core. Thick curves represent the median values of the replicate measurements and horizintal lines the standard error of the replicate measurements. Sites are sorted according to their median EAC\textsubscript{POM}. The depth is presented log-scaled. Different colours indicate samples for which the potential maximum contribution of iron to the EAC or EDC is larger than $\SI{100}{\micro\mol\per\gram\carbon}$.}\label{fig:p-el-depth-profiles-res}
\end{figure}

\begin{figure}[H]

{\centering \includegraphics[width=0.5\textwidth]{001-paper-main_files/figure-latex/p-el-comparison-res-1}

}

\caption{Histograms of the EAC and EDC values, respectively, for the peat POM samples analyzed in this study, humic substances, and dissolved organic matter analysed in other studies. Top: Values reported in $\si{\micro\mol\per\g\sample}$. Bottom: Values reported in $\si{\micro\mol\per\g\carbon}$). Only samples with a potential contribution of iron to the EAC and EDC $\le\SI{100}{\micro\mol\per\gram\carbon}$ are shown.}\label{fig:p-el-comparison-res}
\end{figure}

\hypertarget{relation-to-bulk-chemical-properties}{%
\subsection{Relation to Bulk Chemical Properties}\label{relation-to-bulk-chemical-properties}}

No single bulk chemical property is strongly related to either the EAC\textsubscript{POM}, EDC\textsubscript{POM} or EDC\textsubscript{POM}:EAC\textsubscript{POM} ratio, except for the N:C ratio which is relatively strongly related to the EDC\textsubscript{POM} (\(\rho=\) -0.65), and the H:C ratio which is related to the EAC\textsubscript{POM} (\(\rho=\) -0.47) (figure \ref{fig:p-el-variables1-res}). The EDC\textsubscript{POM}:EAC\textsubscript{POM} ratio is related to the N:C ratio (\(\rho=\) -0.5). All other Pearson correlation coefficients between either the EAC\textsubscript{POM} or EDC\textsubscript{POM} and any of the variables we considered is not larger than 0.45 or smaller than -0.43.\\
The relative weak correlations are not due to non-linear relations, but due to a large variability within and between sites (figure \ref{fig:p-el-variables1-res}). For the EAC\textsubscript{POM}, this variability is especially large for samples with average N:C ratio, medium to large O:C ratio, large C\(_\text{OX}\), and medium HI\(_\text{1630/1090}\). For the EDC\textsubscript{POM}, the variability is large for medium to small O:C ratio, medium to small C\(_\text{OX}\), and medium HI\(_\text{1630/1090}\). For the EDC\textsubscript{POM}:EAC\textsubscript{POM} ratio, the variability is large for small to medium N:C ratios and HI\(_\text{1630/1090}\) (figure \ref{fig:p-el-variables1-res}).\\
EAC\textsubscript{POM} and EDC\textsubscript{POM} values are large along a gradient with large O:C and large H:C ratio at the one end and small O:C and small H:C ratio at the other end (figure \ref{fig:p-el-ch-co1-res}). Conversely, samples with small O:C ratio, but large H:C ratio have the smallest EAC\textsubscript{POM} and EDC\textsubscript{POM}. Whilst this gradient is a general pattern, there are some samples with smaller and larger EAC\textsubscript{POM} and EDC\textsubscript{POM} values than could be expected based on the described gradient. For instance the two samples from SKY I-1 at intermediate depth have a surprisingly small EAC\textsubscript{POM} and EDC\textsubscript{POM}, and samples from SKY II and Martinskapelle (MK) have a large EAC\textsubscript{POM} and EDC\textsubscript{POM} for their small O:C and large H:C ratio (figure \ref{fig:p-el-ch-co1-res}).\\
To compare these patterns to those for HS, we present the same variables in figure \ref{fig:p-el-ch-co1-res} B, but including various IHSS reference HS and measured EAC and EDC values from \textcite{Aeschbacher.2012} for some of these. The H:C values of the HS are separated by \textasciitilde0.5 from that of the peat samples, whereas there is a rather large overlap in the O:C ratio between both sample groups. One exception is the Pony Lake Fulvic Acid (FA) that has a H:C ratio similar to our peat samples. Overall, the HS samples, with their larger EAC and EDC, extent the gradient we observed for the peat samples.
We additionally labeled regions according to OM fractions typically delineated in van-Krevelen diagrams \autocite{Kim.2003}. The peat samples spread between the cellulose and lignin regions, whereas the HS samples are shifted more towards the lignin region due to their small H:C ratios (except Pony Lake FA) (figure \ref{fig:p-el-ch-co1-res} B).

\begin{figure}[H]

{\centering \includegraphics[width=\textwidth]{001-paper-main_files/figure-latex/p-el-variables1-res-1}

}

\caption{Scatterplots of the EAC\textsubscript{POM}, EDC\textsubscript{POM}, and EDC\textsubscript{POM}:EAC\textsubscript{POM} ratio versus various peat properties. Element ratios are molar ratios. "HI" is the ratio of the intensities at 1630 and \SI{1090}{\wn} from mid infrared spectra (larger values indicate more decomposed peat). C$_\text{OX}$ is the nominal oxidation state of carbon (a larger fraction of lipids and lower fraction of carbohydrates decreases its value. Lignin has intermediate C$_\text{OX}$ values) \cite{Masiello.2008}. Only samples with a potential contribution of iron to the EAC and EDC $\le\SI{100}{\micro\mol\per\gram\carbon}$ are shown.}\label{fig:p-el-variables1-res}
\end{figure}

\begin{figure}[H]

{\centering \includegraphics[width=0.5\textwidth]{001-paper-main_files/figure-latex/p-el-ch-co1-res-1}

}

\caption{Van-Krevelen-like plot for the peat samples analysed in this study. \textbf{A:} Points are scaled relative to the EAC and EDC, respectively, and coloured accoring to the sites the samples were taken from. \textbf{B:} The same as A, but including all samples from this study and various IHSS reference humic substances (red and small grey points) in addition to our peat samples (blue points). HS for which Aeschbacher et al. (2012) measured EAC and EDC data are filled red and scaled according to these values. HS for which this was not the case are represented as uniformly small grey points. Moreover, we highlighted regions commonly attributed to different OM fractions in van-Krevelen plots (Kim (2003)). PLFA is the Pony Lake Fulvic Acid reference HS. From this, study, only samples with a potential contribution of iron to the EAC and EDC $\le\SI{100}{\micro\mol\per\gram\carbon}$ are shown and point sizes are scaled relative to the EAC\textsubscript{POM} and EDC\textsubscript{POM}, respectively.}\label{fig:p-el-ch-co1-res}
\end{figure}

This observed gradient is partly also supported by the regression models.
For the EAC\textsubscript{POM}, the H:C ratio has a negative coefficient (\(\beta_\text{H:C}\in\){[}\(-2.58, -0.8\){]}; All reported intervals are 95\%-posterior intervals for the models with all element ratios and Gaussian coefficients, except if stated differently) and the O:C ratio a positive coefficient (\(\beta_\text{O:C}\in\){[}\(0.38, 2.27\){]}) for all models.
For the EDC\textsubscript{POM}, the O:C ratio only has a positive coefficient (\(\beta_\text{O:C}\in\){[}\(0.7, 1.92\){]}) if the N:C and S:C ratio are not included, whereas the coefficients' posterior intervals for the H:C ratio broadly overlaps zero (\(\beta_\text{H:C}\in\){[}\(-1.09, 0.37\){]}). If the N:C and S:C ratio are included in the model, the coefficient for the O:C ratio (\(\beta_\text{O:C}\in\){[}\(-0.64, 1.09\){]}) and H:C ratio (\(\beta_\text{H:C}\in\){[}\(-0.54, 0.93\){]}) clearly overlap zero.\\
For the EAC\textsubscript{POM}, neither the N:C (\(\beta_\text{N:C}\in\){[}\(-0.82, 0.86\){]}), nor the S:C ratio (\(\beta_\text{S:C}\in\){[}\(-0.17, 0.74\){]}) have a clearly from zero different coefficient. For the EDC\textsubscript{POM}, the S:C ratio is also not clearly different from zero (\(\beta_\text{S:C}\in\){[}\(-0.32, 0.7\){]}), whereas the model implies a negative relation for the N:C ratio (\(\beta_\text{N:C}\in\){[}\(-2.55, -0.63\){]}). Thus, it seems that the EAC\textsubscript{POM} is linearly mainly related to the H:C and O:C ratio, whereas the EDC\textsubscript{POM} is mainly related to the N:C ratio.

\hypertarget{relation-to-molecular-structures-1}{%
\subsection{Relation to Molecular Structures}\label{relation-to-molecular-structures-1}}

MIR variables typically assigned to labile OM fractions tend to be positively related to the EAC\textsubscript{POM} and EDC\textsubscript{POM} and variables typically assigned to more recalcitrant OM fractions tend to be negatively related to the EAC\textsubscript{POM} and EDC\textsubscript{POM} (figure \ref{fig:p-mir-cor-res}). This is evident from positive correlations with MIR variables representing cellulose C-O stretching, phenol C-O stretching and O-H bending, carbonyl C=O stretching, cellulose and phenol O-H stretching and negative correlations with MIR variables representing aromatic C=C stretching, C-H bending, and lipid C-H stretching \autocite{Stuart.2005,Cocozza.2003,Artz.2008,Kubo.2005,Schmidt.2006}. However, the correlations are overall relatively small (maximum absolute correlation \(=0.61\)).\\
The general patterns in the correlation spectra for the EAC\textsubscript{POM} are similar to those for the EDC\textsubscript{POM}. Some deviations are visible (figure \ref{fig:p-mir-cor-res}): For example the EDC\textsubscript{POM} has a more negative relation to aromatic C=C stretching, and a more positive relation to cellulose and phenol O-H stretching, whereas the EAC\textsubscript{POM} is more strongly related to carbonyl C=O stretching.\\
Variable selection during the regression analysis identified 6 and 2 variables as sufficient to predict the EAC\textsubscript{POM} and EDC\textsubscript{POM}, respectively: The EAC\textsubscript{POM} is positively related to carbonyl group C=O stretching and tends to be negatively related to lipid C-H stretching, O-H stretching of unbonded OH groups, and C-H bending of (potentially polysubstituted) aromatics (table \ref{tab:t-mir-sel}). For lipid C-H stretching and unbonded O-H stretching, two directly neighboring variables with partly contrasting coefficients (positive and negative) were selected. However, their joint relation to the EAC\textsubscript{POM} is clearly negative (supplementary figure \ref{fig:p-partial-dependence-res}). The EDC\textsubscript{POM} tends to be positively related to O-H stretching of intramoleculary bonded OH groups, probably of cellulose and phenols, and tends to be negatively related to secondary amide N--H bending and C--N stretching (table \ref{tab:t-mir-sel}).\\
Overall, this indicates that the EAC\textsubscript{POM} is positively related to carbonyl groups and negatively related to structures more abundant in decomposed peat (lipids, aromatics, unbonded OH groups), and the EDC\textsubscript{POM} is positively related to structures more abundant in undecomposed peat (intramolecular OH bonds in cellulose and phenols).

\begin{figure}[H]

{\centering \includegraphics[width=\textwidth]{001-paper-main_files/figure-latex/p-mir-cor-res-1}

}

\caption{Pearson correlation spectra for the EAC\textsubscript{POM} and EDC\textsubscript{POM}, respectively. Each point on the lines represents the Pearson correlation coefficient at the respective wavenumber. The uppermost grey line is an arbitrary reference MIR spectrum from the data set plotted to facilitate interpretation. Correlation coefficients were computed for samples with a potential contribution of iron to the EAC and EDC $\le\SI{100}{\micro\mol\per\gram\carbon}$.}\label{fig:p-mir-cor-res}
\end{figure}

\begin{table}

\caption{\label{tab:t-mir-sel}Assignment of MIR variables included in the projected regression models for the EAC\textsubscript{POM} and EDC\textsubscript{POM} using the filtered data set, respectively. "Wavenumber" represents the average bin position wavenumber value of the MIR variable that were selected. "Coefficient" are the estimated coefficients of the variables (mean and limits of the 95\% posterior intervals).}
\centering
\resizebox{\linewidth}{!}{
\begin{tabular}[t]{cll>{\raggedright\arraybackslash}p{4cm}>{\raggedright\arraybackslash}p{3cm}}
\toprule
\multicolumn{1}{c}{ } & \multicolumn{2}{c}{Coefficient} & \multicolumn{1}{c}{ } & \multicolumn{1}{c}{ } \\
\cmidrule(l{3pt}r{3pt}){2-3}
Wavenumber & EAC\textsubscript{POM} & EDC\textsubscript{POM} & Assigned structure & Reference\\
\midrule
830 & -0.13 (-0.28, 0.03) &  & C-H bending of di- or trisubstituted aromatics & \textcite{Stuart.2005}\\
1530 &  & -0.23 (-0.68,0.17) & Secondary amide N–H bending and C–N stretching & \textcite{Stuart.2005}\\
1720 & 0.41 (0.19, 0.62) &  & Carbonyl C=O stretching (carboxyls, esters, ketones - aliphatic and aromatic) & \textcite{Cocozza.2003}, \textcite{Stuart.2005}, \textcite{Artz.2008}\\
2890 & -0.71 (-1.1, -0.28) &  & Lipid C-H stretching & \textcite{Cocozza.2003}, \textcite{Stuart.2005}, \textcite{Artz.2008}\\
2910 & 0.1 (-0.27, 0.45) &  & Lipid C-H stretching & \textcite{Cocozza.2003}, \textcite{Stuart.2005}, \textcite{Artz.2008}\\
\addlinespace
3370 &  & 0.34 (-0.09,0.75) & O-H  stretching of bonded OH groups (cellulose, phenols) & \textcite{Stuart.2005} \textcite{Kubo.2005} \textcite{Schmidt.2006}\\
3660 & 1.45 (-0.84, 3.58) &  & O-H stretching of unbonded OH groups & \textcite{Stuart.2005}, \textcite{Kubo.2005}, \textcite{Schmidt.2006}\\
3670 & -1.88 (-4.02, 0.42) &  & O-H stretching of unbonded OH groups & \textcite{Stuart.2005}, \textcite{Kubo.2005}, \textcite{Schmidt.2006}\\
\bottomrule
\end{tabular}}
\end{table}

\hypertarget{predictive-accuracy-of-the-mirs-based-models-in-comparison-to-regression-models-based-on-element-ratios}{%
\subsection{Predictive Accuracy of the MIRS-Based Models in Comparison to Regression Models Based on Element Ratios}\label{predictive-accuracy-of-the-mirs-based-models-in-comparison-to-regression-models-based-on-element-ratios}}

The predictive performances of the different modeling approaches (MIRS-based vs element ratio-based) do not differ considerably and are several times larger than the standard deviation of the distributions for the respective replicate measurements. The MIRS-based models had a median 10-fold CV-RMSE \(23.5\) and \(\SI{4.4}{\micro\mol\per\g\carbon}\) smaller and larger than the element ratio-based models for the EAC\textsubscript{POM} and EDC\textsubscript{POM}, respectively. The models with the least median 10-fold CV-RMSE for each variable had a 10-fold CV-RMSE of 250.4 {[}101.3, 509{]} and 160.5 {[}58.1, 279.7{]} \(\si{\micro\mol\per\g\carbon}\) for the EAC\textsubscript{POM} and EDC\textsubscript{POM}, respectively. In comparison to this, the median standard deviation from the estimated distribution for the measured values is 36.2 and \(\SI{21.2}{\micro\mol\per\g\carbon}\). In spite of the similar predictive performance of both models for the EAC\textsubscript{POM}, the MIRS-based model is clearly less biased than the element ratio-based model, whereas both models for the EDC\textsubscript{POM} are clearly biased (figure \ref{fig:p-y-yhat-res}).\\
Using derivative spectra, data subsets, or PLSR instead of Bayesian regularization neither yield considerably worse, nor better models in terms of their training predictive accuracy (supplementary figure \ref{fig:p-cal-elpd-res}). The projected models based on the PLSR reference model comprise more variables than that based on Bayesian regularization for the EAC\textsubscript{POM} (38 in comparison to 6 for non-derived spectra). For the EDC\textsubscript{POM}, the differences are smaller.

\begin{figure}[H]

{\centering \includegraphics[width=0.6\textwidth]{001-paper-main_files/figure-latex/p-y-yhat-res-1}

}

\caption{Plot of measured values versus fitted values for the regression models predicting the EAC\textsubscript{POM} and EDC\textsubscript{POM} using the filtered data set. Rows contain plots for the two different modeling approaches: "Element ratios" indicates the regression models using all four element ratios (H:C, O:C, N:S, S:C ratio) as predictor variables, and "MIRS" the full regression models using non-derived mid infrared spectra. Error bars represent 95\% predictive intervals for the measured and predicted values. Points on the diagonal lines represents identical measured and fitted values.}\label{fig:p-y-yhat-res}
\end{figure}

\hypertarget{discussion}{%
\section{Discussion}\label{discussion}}

To answer how peat chemistry relates to its EAC\textsubscript{POM} and EDC\textsubscript{POM} and how decomposition changes both, we first outline that our results imply quinones and phenols as major contributors to peat EAC\textsubscript{POM} and EDC\textsubscript{POM}. Thereafter, we outline how differences in vegetation chemistry and effects of decomposition on the EAC\textsubscript{POM} and EDC\textsubscript{POM} can result in the decoupling of peat EAC\textsubscript{POM} and EDC\textsubscript{POM}; we explain the large depth-related variability of both, stronger relations of the EDC\textsubscript{POM} to the N:C ratio, weak relations of the EAC\textsubscript{POM}, EDC\textsubscript{POM}, and EDC\textsubscript{POM}:EAC\textsubscript{POM} ratio to HI\(_\text{1630/1090}\) and element ratios. We summarize these findings in a conceptual model that proposes vegetation chemistry and intensity of aerobic decomposition as major factors that control peat EAC\textsubscript{POM} and EDC\textsubscript{POM}.
Finally, we discuss that our MIRS-based regression models can be used as screening tool for prediction of the EAC\textsubscript{POM}, but not the EDC\textsubscript{POM}.\\
The analyzed peat samples cover a globally representative range of mid to high latitude peat properties and degrees of decomposition (table \ref{tab:t-ranges-sites}).
The element ratio data are within the ranges reported by several larger compilations of peat chemical properties \autocite{Moore.2018,Leifeld.2020,Wang.2015b,Loisel.2014,Tipping.2016}. The same is true for C\(_\textrm{OX}\) values \autocite{Worrall.2016b,Moore.2018,Leifeld.2020}. Overall, we are confident that our findings and interpretations should hold for a broad range of peat materials and thus are generalizable.

\hypertarget{quinones-and-phenols-are-main-contributors-to-peat-eac-and-edc}{%
\subsection{\texorpdfstring{Quinones and Phenols are Main Contributors to Peat EAC\textsubscript{POM} and EDC\textsubscript{POM}}{Quinones and Phenols are Main Contributors to Peat EAC and EDC}}\label{quinones-and-phenols-are-main-contributors-to-peat-eac-and-edc}}

Our results point towards quinones and phenols as main contributors to the EAC\textsubscript{POM} and EDC\textsubscript{POM} of peat, respectively. EAC\textsubscript{POM} and EDC\textsubscript{POM} values are large along a H:C-O:C gradient with large O:C and large H:C ratio at the one end and small O:C and small H:C ratio at the other end (figure \ref{fig:p-el-ch-co1-res}). Based on commonly delineated H:C-O:C regions in van-Krevelen diagrams \autocite{Kim.2003}, we assume that this gradient characterizes material rich in polymeric quinones and phenols. This interpretation is also supported by the positive relation to carbonyl groups which are characteristic of polymeric quinones and phenols \autocite{ElMansouri.2007} (figure \ref{fig:p-mir-cor-res}). In addition, the more pronounced negative correlation of the EDC\textsubscript{POM} to the N:C ratio in comparison to the EAC\textsubscript{POM} can be explained with the larger susceptibility of phenols towards decomposition in contrast to quinones which are formed by partial oxidation of phenols \autocite{Fenner.2011,Aeschbacher.2012,Bolton.2018}. We expected this finding since quinones and phenols have been identified as major contributors to OM EAC and EDC in general \autocite{Ratasuk.2007,Aeschbacher.2010,Aeschbacher.2012}.\\
We did not find clear relations of the N:C or S:C ratio to the EAC\textsubscript{POM} and EDC\textsubscript{POM} that would point towards a large contribution of non-quinone moieties to the EAC\textsubscript{POM} or EDC\textsubscript{POM}. In fact, the N:C ratio is negatively related to the EDC. A small non-quinone EAC and EDC is in line with the relative small S and N contents of the peat samples and the neutral pH value our measurements were standardized to \autocite{Fimmen.2007,HernandezMontoya.2012}; non-quinone EAC\textsubscript{POM} and EDC\textsubscript{POM} would likely be larger with smaller pH values \autocite{Fimmen.2007,HernandezMontoya.2012,Aeschbacher.2012}. Moreover, it is likely that any relation between the N:C and S:C ratio and non-quinone EAC\textsubscript{POM} and EDC\textsubscript{POM} is confounded by the dependence of these element ratios and the quinone EAC\textsubscript{POM} and EDC\textsubscript{POM} on the degree of decomposition \autocite{Biester.2014} (see below).

\hypertarget{vegetation-chemistry-and-decomposition-cause-the-decoupling-of-peat-eac-and-edc}{%
\subsection{\texorpdfstring{Vegetation Chemistry and Decomposition Cause the Decoupling of Peat EAC\textsubscript{POM} and EDC\textsubscript{POM}}{Vegetation Chemistry and Decomposition Cause the Decoupling of Peat EAC and EDC}}\label{vegetation-chemistry-and-decomposition-cause-the-decoupling-of-peat-eac-and-edc}}

The above supported and widely accepted hypothesis that quinones are main contributors to the EAC of OM and hydroquinones and phenols are main contributors to the EDC of OM implies that differences in peat EAC\textsubscript{POM} and EDC\textsubscript{POM} are controlled by different amounts of polymeric quinones and phenols. The amount of polymeric quinones and phenols in peat is controlled by the amount of these moieties in the vegetation that initially formed the peat, and decomposition processes that are known to result in the partial oxidation or mineralization of these moieties. We therefore argue that the magnitude, decoupling, and depth-related changes in peat EAC\textsubscript{POM} and EDC\textsubscript{POM} we observed are caused by differences in the chemistry of the peat forming vegetation and the intensity and pathways of decomposition processes.\\
The decoupling of peat EAC\textsubscript{POM} and EDC\textsubscript{POM} can be explained by the joint effects of vegetation polymeric phenol contents and transformation of phenols to quinones during decomposition. It has been suggested that undecomposed plant-derived polymeric aromatics, such as lignin, have large contents of phenols, but small contents of quinones, which results in an initially large EDC, but small EAC \autocite{Aeschbacher.2012}. Decomposition and oxidation of the polymeric phenols decreases their fraction, but can increase the relative (and absolute) amount of quinones \autocite{Aeschbacher.2012,Bolton.2018,LaCroix.2020}. These mechanisms have four important implications: First, undecomposed samples have a maximum EDC, second, this maximum EDC varies depending on the vegetation polymeric phenol content, third, decomposition of polymeric phenols decreases the EDC and increases the EAC \autocite{Aeschbacher.2012}, and fourth, the initial EDC defines the maximum potential EAC of a sample. This explains why a decoupling of the EAC and EDC can be observed for HS and DOM \autocite{Aeschbacher.2012}. Our measurements fit into the EDC-EAC gradient observed for HS and DOM (supporting figure \ref{fig:p-el-eac-edc2-res}) and we therefore conclude that the decoupling of peat EAC\textsubscript{POM} and EDC\textsubscript{POM} is caused by the same mechanisms.

\hypertarget{interactions-of-vegetation-chemistry-and-decomposition-cause-weak-relations-of-electrochemical-properties-to-pom-chemistry}{%
\subsection{Interactions of Vegetation Chemistry and Decomposition Cause Weak Relations of Electrochemical Properties to POM Chemistry}\label{interactions-of-vegetation-chemistry-and-decomposition-cause-weak-relations-of-electrochemical-properties-to-pom-chemistry}}

\hypertarget{the-degree-of-decomposition-confounds-how-the-hc-ratio-represents-phenols-and-quinones}{%
\subsubsection{The Degree of Decomposition Confounds How the H:C ratio Represents Phenols and Quinones}\label{the-degree-of-decomposition-confounds-how-the-hc-ratio-represents-phenols-and-quinones}}

The conceptual understanding how initial OM polymeric phenol content and decomposition cause the decoupling between EAC and EDC has been developed for HS \autocite{Aeschbacher.2012}. However, our peat samples cover a more variable gradient of contents of polymeric quinones and phenols, polysaccharides, and lipids than previously analyzed HS, as indicated by the smaller correlation between the POM H:C and O:C ratios (figure \ref{fig:p-el-ch-co1-res}). Even though Pony Lake FA has an extremely large H:C ratio for its intermediate O:C ratio in comparison to other studied HS, its H:C ratio is smaller than that of all other previously analyzed HS \autocite{Aeschbacher.2012,HuffmanLaboratories.NA}. For this reason, it does not overlap with other HS on the H:C gradient which represents the polymeric quinone and phenol content \autocite{Aeschbacher.2010}. In other terms, for the peat POM samples, the same H:C ratio can represent samples with either large O:C ratio or small O:C ratio, corresponding either to relatively undecomposed samples rich in polysaccharides or to strongly decomposed samples rich in lipids \autocite{Kim.2003,Leifeld.2012,Bader.2018}. It is likely that the same pattern caused the relative weak relation \textcite{Tan.2017} observed for the EAC of HS to the H:C ratio. Thus, the H:C ratio does represent a gradient in polymeric phenol and quinone content, as for previously analyzed HS, but is confounded by a gradient in the degree of decomposition.\\
This confounding effect of the degree of decomposition on the H:C ratio results in a weaker correlation of the EAC\textsubscript{POM} to the H:C ratio than for previously studied HS \autocite{Aeschbacher.2010}. Figure \ref{fig:p-el-ch-co1-res} B shows that peat samples with the same H:C ratio tend to have a smaller EAC\textsubscript{POM} if they contain a larger amount of lipids and smaller amount of polysaccharides (smaller O:C ratio). This is also indicated by the negative relation of MIRS variables related to lipids to the EAC\textsubscript{POM} and EDC\textsubscript{POM} (figure \ref{fig:p-mir-cor-res}, table \ref{tab:t-mir-sel}) and by the fact that in the regression models the H:C and O:C ratio are jointly related to the EAC\textsubscript{POM}. Thus, since differences in the O:C ratio are linked to differences in the EAC\textsubscript{POM}, and since such samples are present within our data set, we found a weaker relation of the EAC\textsubscript{POM} to the H:C ratio.

\hypertarget{explaining-weak-relations-of-peat-eac-and-edc-with-hi_text16301090-nc-ratio-and-c_textox}{%
\subsubsection{\texorpdfstring{Explaining Weak Relations of Peat EAC\textsubscript{POM} and EDC\textsubscript{POM} with HI\(_\text{1630/1090}\), N:C ratio, and C\(_\text{OX}\)}{Explaining Weak Relations of Peat EAC and EDC with HI\_\textbackslash text\{1630/1090\}, N:C ratio, and C\_\textbackslash text\{OX\}}}\label{explaining-weak-relations-of-peat-eac-and-edc-with-hi_text16301090-nc-ratio-and-c_textox}}

Looking at the relation of the EAC\textsubscript{POM} and H:C and O:C ratio as above, but focusing on samples with a similar and low O:C ratio we can exemplarily illustrate why the EAC\textsubscript{POM} is only weakly related to HI\(_\text{1630/1090}\), N:C ratio, and C\(_\text{OX}\). Overall, the O:C ratio is strongly related to HI\(_\text{1630/1090}\) (\(\rho=-0.82\)), the N:C ratio (\(\rho=-0.68\)), and C\(_\text{OX}\) (\(\rho=0.87\)). However, a medium to small O:C ratio (HI\(_\text{1630/1090}\)/N:C ratio/C\(_\text{OX}\)) may either represent peat with a large amount of polymeric quinones and large EAC\textsubscript{POM} (small H:C ratio) or peat with a large amount of lipids and small EAC\textsubscript{POM} (large H:C ratio) (figure \ref{fig:p-el-ch-co1-res} B). For this reason, the EAC\textsubscript{POM} can vary considerably across a broad range of HI\(_\text{1630/1090}\) and N:C ratios as observed in our peat samples under study (figure \ref{fig:p-el-variables1-res}).\\
For the EDC\textsubscript{POM}, this confounding effect is less relevant since the EDC\textsubscript{POM} is negatively affected by decomposition, irrespective if the resulting peat is rich in lipids or polymeric quinones, as mentioned above \autocite{Fenner.2011,Bolton.2018}. This is evident from the stronger relation of the EDC\textsubscript{POM} to the N:C ratio (\(\rho=-0.69\)). Since samples with a small O:C ratio that are rich in polymeric quinones and phenols nevertheless have a larger EDC\textsubscript{POM}, and since the HI\(_\text{1630/1090}\) and C\(_\text{OX}\) do separate these samples less clearly from the lipid rich samples than the N:C ratio (figure \ref{fig:p-el-variables1-res}), the relation of both the HI\(_\text{1630/1090}\) and C\(_\text{OX}\) is also weak for the EDC\textsubscript{POM}, similarly to the EAC\textsubscript{POM}.

\hypertarget{which-factors-determine-the-polymeric-phenol-and-quinone-content-of-decomposed-pom}{%
\subsubsection{Which Factors Determine the Polymeric Phenol and Quinone Content of Decomposed POM?}\label{which-factors-determine-the-polymeric-phenol-and-quinone-content-of-decomposed-pom}}

The question remains which factors determine if a sample with a larger degree of decomposition is either rich in polymeric quinones and phenols --- thus having a larger EAC\textsubscript{POM} and EDC\textsubscript{POM} --- or rich in lipids --- thus having the minimal EAC\textsubscript{POM} and EDC\textsubscript{POM}. Both, differences in vegetation chemistry and decomposition, may result in the observed differences in lipid versus polymeric quinone and phenol content.\\
We cannot definitely disentangle both factors based on our data since we neither have complete information about the peat forming vegetation, nor the actual predominant decomposition processes, but there is some evidence that both may contribute. First of all, the samples with the smallest H:C ratio probably contain larger amounts of wood and root remains from trees and shrubs (e.g.~both Lutose sites, especially the deepest samples \autocite{Heffernan.2020}; P. Brunswick \autocite{Broder.2012}; Mer Bleue, deepest sample \autocite{Elliott.2012}) which is a plausible explanation for their large EAC\textsubscript{POM}. In contrast, samples with approximately the same O:C ratio, but a larger H:C ratio are probably formed by sedges and (minerotrophic) \emph{Sphagnum} mosses (samples from both both fen sites (Touxi, Dongtu), or from the two Patagonian bogs SKY I-1 and SKY I-6) and likely strongly decomposed (TX, DT) or known to be strongly decomposed (Both SKY I sites and SKY II, \textcite{Broder.2012}). Second, it has been shown that intense aerobic decomposition of peat under drainage results in a larger H:C ratio of more decomposed peat, whereas less oxic conditions result in a decrease of the H:C ratio during decomposition \autocite{Leifeld.2012}. A plausible and likely explanation therefore is that aerobic decomposition of POM initially rich in polymeric phenols results in a large amount of quinones and therefore a large EAC\textsubscript{POM}, whereas \emph{intense} aerobic decomposition of POM that already had small initial amounts of polymeric phenols results in a large amount of lipids. Conversely, anaerobic decomposition may conserve initial polymeric phenols and quinones and thus EAC\textsubscript{POM} and EDC\textsubscript{POM} (see below). This means that both vegetation chemistry and intensity of aerobic decomposition contribute to the observed pattern.

\hypertarget{differential-effects-of-decomposition-on-peat-eac}{%
\subsubsection{\texorpdfstring{Differential Effects of Decomposition on Peat EAC\textsubscript{POM}}{Differential Effects of Decomposition on Peat EAC}}\label{differential-effects-of-decomposition-on-peat-eac}}

The hypothesis that vegetation chemistry and decomposition intensity together change peat phenols and quinone content can help resolving the apparent contradiction we have produced: Partial oxidation of phenols to quinones during decomposition increases the EAC\textsubscript{POM} \autocite{Aeschbacher.2012,Walpen.2018,Tan.2017}, but typical MIRS-derived decomposition indicators such as the amount of lipids, unbonded OH groups, and aromatic backbone structures \autocite{Cocozza.2003,Artz.2008} are negatively related to the EAC\textsubscript{POM} (table \ref{tab:t-mir-sel}). According to our conceptual understanding, the contradiction is only apparent: Aerobic decomposition of POM initially rich in polymeric phenols and quinones increases the amount of quinones \autocite{Aeschbacher.2012}, as indicated by larger amounts of carbonyl groups (table \ref{tab:t-mir-sel}). Intense aerobic decomposition of POM with initially low amounts of polymeric phenols and quinones (and hence larger amounts of polysaccharides) results in the mineralization of polysaccharides, phenols and quinones and the accumulation of lipids \autocite{Fenner.2011,Leifeld.2012}. Thus, if a specific peat contains large amounts of lipids and has an amorphous structure, this indicates that it also contains low amounts of polymeric phenols and quinones because it experienced intense decomposition.

\hypertarget{a-conceptual-model-for-peat-eac-and-edc}{%
\subsection{\texorpdfstring{A conceptual model for peat EAC\textsubscript{POM} and EDC\textsubscript{POM}}{A conceptual model for peat EAC and EDC}}\label{a-conceptual-model-for-peat-eac-and-edc}}

To summarize our findings, we propose the conceptual model shown in figure \ref{fig:conceptual1} (an additional representation is shown in supplementary figure \ref{fig:conceptual2} and additional processes that may change peat EAC\textsubscript{POM} and EDC\textsubscript{POM}, but have not been discussed in more detail yet, are presented in the supplementary information). We hypothesize that both the polymeric phenol content of the peat forming vegetation and the intensity of decomposition processes are the most important factors controlling the EDC\textsubscript{POM} and EAC\textsubscript{POM} of peat. Moreover, both factors likely interact since peat with initially large amounts of polymeric phenols has a smaller decomposition rate \autocite{Bengtsson.2018}.\\
Wood and roots from trees and shrubs are probably the plant remains with the largest fraction of polymeric phenols \autocite{Benner.1984,Williams.1998,Strakova.2010,Hodgkins.2018}, whereas other vascular plants and mosses have variable and partly smaller amounts of polymeric phenols \autocite{Williams.1998,Scheffer.2001,Strakova.2010,Bengtsson.2018,Zak.2019}. For this reason, peat with larger contributions of wood or roots e.g.~from shrubs (and potentially some graminoid or moss species) likely has the largest initial EDC\textsubscript{POM} and upon decomposition the largest potential EAC\textsubscript{POM} (figure \ref{fig:conceptual1} and supplementary figure \ref{fig:conceptual2}). We propose that standardized measurements of electrochemical properties for different peat forming species are required to provide a quantitative basis for this hypothesis.\\
Under anoxic conditions, low phenol oxidase activities and the effects this has on other enzymes required for biomass breakdown \autocite{Fenner.2011} make peat material keep its initial EDC\textsubscript{POM} and EAC\textsubscript{POM}. In addition, quinone formation by partial oxidation is limited under such conditions, such that the EDC\textsubscript{POM} should be relative large, whereas the EAC\textsubscript{POM} remains smaller (figure \ref{fig:conceptual1} and supplementary figure \ref{fig:conceptual2}). A factor that may decrease both the EAC\textsubscript{POM} and EDC\textsubscript{POM} under such conditions are condensation reactions \autocite{Hotta.2002,Uchimiya.2009,Bolton.2018,Zhao.2020,Olk.2006,Heitmann.2006,Yu.2016}. Conversely, faster degradation of polysaccharides may increase the EAC\textsubscript{POM} and EDC\textsubscript{POM} since this results in a relative increase of phenols and quinones \autocite{Benner.1984}. However, it remains currently unclear to which extent both factors may play a role under anoxic conditions.
Thus, we assume that under anoxic conditions the initial vegetation properties largely control peat electrochemical properties.\\
Under oxic conditions, increased phenol oxidase activities result in an oxidative transformation of polymeric phenols to quinones \autocite{Fenner.2011,Schellekens.2015,Bolton.2018}. This can increase the EAC\textsubscript{POM} and decrease the EDC\textsubscript{POM}. If under these oxic conditions e.g.~large temperatures, large concentrations of nutrients, large amounts of labile OM, high pH values, or other factors further facilitate the mineralization of polymeric phenols \autocite{Bragazza.2007,Fenner.2011,Kang.2018c,Bowring.2020}, coupling reactions \autocite{Hotta.2002,Johnson.2015,Bolton.2018,Zhao.2020}, and other condensation reactions \autocite{Bolton.2018,Olk.2006,Heitmann.2006,Yu.2016}, both the EAC\textsubscript{POM} and EDC\textsubscript{POM} may decrease (figure \ref{fig:conceptual1} and supplementary figure \ref{fig:conceptual2}). Intense break-down of cell wall structures (as implied by our regression models for the EDC\textsubscript{POM} and EAC\textsubscript{POM}) may has an important role since it increases the surface of the polymeric phenols exposed for oxidation or condensation reactions \autocite{Tsuneda.2001}. Just as under anoxic conditions, a decrease in the EAC\textsubscript{POM} and EDC\textsubscript{POM} may be offset by faster mineralization of polysaccharides than polymeric phenols \autocite{Benner.1984}. However, again it remains currently unclear to which extent this factor and also condensation reactions play a role. Moreover, it is unclear if partial oxidation of polymeric phenols is as slow as its complete mineralization or may be comparable to polysaccharide oxidation. This would decrease the potential effect enhanced polysaccharide mineralization would have. Thus, we assume that oxic conditions increase the EAC\textsubscript{POM} at the expense of the EDC\textsubscript{POM}. The initial content of polymeric phenols defines the maximum EAC\textsubscript{POM} peat can attain throughout this process which results in variable responses of the peat EAC\textsubscript{POM} and EDC\textsubscript{POM} to decomposition. Intense aerobic decomposition, especially of material with low initial amounts of polymeric phenols, may even decrease the EAC due to mineralization and condensation of polymeric phenols.

\begin{figure}[H]

{\centering \includegraphics[width=1\linewidth]{./../figures/conceptual_vegetation_decomposition1}

}

\caption{Conceptual description of the assumed effects of vegetation chemistry (polymeric phenol content) and decomposition pathways and intensity on peat chemistry and its EAC and EDC. Note that the assignment of plant taxa and their polymeric phenol contents is only an example as the chemical properties may be highly diverse within taxa \autocite{Bengtsson.2018}.}\label{fig:conceptual1}
\end{figure}

\hypertarget{mirs-based-regression-models-can-predict-peat-eac}{%
\subsection{\texorpdfstring{MIRS-Based Regression Models can Predict Peat EAC\textsubscript{POM}}{MIRS-Based Regression Models can Predict Peat EAC}}\label{mirs-based-regression-models-can-predict-peat-eac}}

We suggest that our modeling approach is a proof-of-concept that peat EAC\textsubscript{POM} can be predicted from MIRS. The MIRS-based model had the smallest average RMSE, albeit the RMSE for both the MIRS-based model and the element ratio-based model were relatively large and their 95\%-posterior intervals broad and strongly overlapping. During graphical model validation, we observed that the element ratio-based model had a considerably larger bias than the MIRS-based model (figure \ref{fig:p-y-yhat-res}), suggesting that the MIRS-based model overall is more accurate and robust.\\
In contrast to this, both element ratio-based and MIRS-based regression models failed to adequately capture the variability in the EDC\textsubscript{POM} (figure \ref{fig:p-y-yhat-res}). Since the EDC\textsubscript{POM} of our samples in their oxidized state was smaller, the relative large predictive uncertainties turn both models unsuitable for practical applications.
Potential reasons for the differential performances of the models are discussed in the supporting information.

\hypertarget{conclusions}{%
\section{Conclusions}\label{conclusions}}

Our research question was how peat chemistry relates to its EAC\textsubscript{POM} and EDC\textsubscript{POM} and how decomposition changes both. Our results show that peat EAC\textsubscript{POM} and EDC\textsubscript{POM} are smaller than HS and DOM EAC and EDC, show no uniform gradients with peat depth, and are highly variable both within and between sites. Both are positively related to the relative amount of carbonyls and relatively intact cell-wall structures, and negatively related to the amounts of lipids and aromatic backbone structures. Whereas the EDC\textsubscript{POM} is negatively related to the N:C ratio, the EAC\textsubscript{POM} is not. Relations of the EAC\textsubscript{POM} and EDC\textsubscript{POM} to other decomposition indicators, element ratios, C\(_\text{OX}\), and even molecular structures were generally weak, partly in contrast to existing studies for DOM.\\
We hypothesize a conceptual model that describes how vegetation chemistry and intensity of aerobic decomposition control peat EAC\textsubscript{POM} and EDC\textsubscript{POM}. Undecomposed peat formed by vegetation rich in polymeric phenols has the largest EDC\textsubscript{POM}. Decomposition of such material results in peat with the largest EAC\textsubscript{POM}, but decreases the EDC\textsubscript{POM}. In contrast, peat formed by vegetation with small amounts of polymeric phenols generally has a smaller EAC\textsubscript{POM} and EDC\textsubscript{POM}. Especially for such material, intense decomposition not only decreases the EDC\textsubscript{POM}, but potentially also the EAC\textsubscript{POM}. This model can plausibly explain the large variability in the relation of the EAC\textsubscript{POM} and EDC\textsubscript{POM} to peat chemical properties, decomposition indicators, and molecular structures, as well as the high intra-site variability and decoupling of the EAC\textsubscript{POM} and EDC\textsubscript{POM}.
Finally, we provide a proof-of-concept that MIRS-based regression models may be at least suitable as screening tools to predict peat EAC\textsubscript{POM}.\\
Our study has four major limitations: First, it is difficult to completely exclude contributions of iron to our estimates for the EAC\textsubscript{POM} and EDC\textsubscript{POM}.Second, we derived our conceptual understanding on purely observational data without experimental control. Third, we had only partly data on palaeovegetation and thus could only partly establish direct links between vegetation and peat chemistry. Fourth, we conducted EAC\textsubscript{POM} and EDC\textsubscript{POM} measurements under standardized conditions which impedes deriving direct environmental implications of our findings.\\
Partly, these limitations were practically unavoidable to ensure comparability of results or their representativeness for broad environmental conditions and peat chemical properties and degrees of decomposition. Moreover, due to the scarce knowledge on the relation between EAC\textsubscript{POM} and EDC\textsubscript{POM} to peat chemistry and decomposition, an explorative analysis is a suitable first step towards developing conceptual and quantitative knowledge and our conceptual model provides opportunities to develop testable hypotheses to guide future experimental research. Further research is necessary to disentangle contributions from iron and OM to the EAC and EDC, and we assumed that the induced bias is generally low and does not confound our conceptual model.\\
Our results imply that peat EAC\textsubscript{POM} and EDC\textsubscript{POM} can be spatially and temporally highly variable and that it is difficult to predict based on peat bulk properties. This furthermore implies that the potential for CH\(_4\) suppression due to POM reduction may be similarly variable and difficult to predict.\\
Therefore, spatially resolved measurements or the incorporation of our hypothesized conceptual understanding into process models are required for the accurate quantification of peat EAC\textsubscript{POM} and EDC\textsubscript{POM} and their potential effects on redox processes, particularly CH\(_4\) formation. We hope that our results, conceptual model, and MIRS-based models facilitate this work and contribute to the understanding of peatland-climate interactions.

\hypertarget{data-and-code-availability}{%
\section*{Data and code availability}\label{data-and-code-availability}}
\addcontentsline{toc}{section}{Data and code availability}

Data and code to reproduce this document are available as research compendium on {[}--- todo: add link to GitHub repo, todo: add DOI{]}. In addition, the MIRS-based reference models based on Bayesian regularization for both the EAC\textsubscript{POM} and EDC\textsubscript{POM} are available via the R package irpeat \autocite{Teickner.2020b} {[}---todo: add version tag on GitHub{]}. These models can be readily used for predictions with own data.

\hypertarget{author-contributions}{%
\section*{Author contributions}\label{author-contributions}}
\addcontentsline{toc}{section}{Author contributions}

HT (conceptualization, data curation, formal analysis, investigation, methodology, software, validation, visualization, writing - original draft, writing -- review \& editing). CG (conceptualization, investigation, methodology, writing -- review \& editing), KHK (conceptualization, funding acquisition, methodology, project administration, resources, supervision, writing - original draft, writing -- review \& editing).

\hypertarget{acknowledgements}{%
\section*{Acknowledgements}\label{acknowledgements}}
\addcontentsline{toc}{section}{Acknowledgements}

For their support during sample collection/provision, we would like to thank Svenja Agethen (DE), Werner Borken (SKY I-1, SKY I-6), Tanja Broder (PBR, SKY II, LT, MK), Mariusz Gałka (LT, MK), Liam Heffernan (LP, LB), Norbert Hölzel (KR, ISH), Annkathrain Hömberg (TX, DT), Tim Moore (MB), Sindy Wagner (BB), Tim-Martin Wertebach (KR, ISH), and Zhi-Guo Yu (TX, DT).\\
Analyses of this study were carried out in the laboratory of the Institute of Landscape Ecology. Svenja Agethen and Michael Sander provided analytical support. The assistance of Ulrike Berning-Mader, Madeleine Supper, Victoria Ratachin, and numerous student assistants is greatly acknowledged. We thank Dr.~Hendrik Wetzel, Fraunhofer Institute for Applied Polymer Research, Dept. Starch Modification/Molecular Properties, Potsdam, Germany, for analysis of O and H. The workflow was reproduced by the Reproducible Research Support Service of the University of Münster.\\
This Study was funded by the Deutsche Forschungsgemeinschaft (DFG, German Research Foundation) grant no. KN 929/12-1 to Klaus-Holger Knorr; Chuanyu Gao was supported by the Youth Innovation Promotion Association CAS (No.~2020235).

\hypertarget{references}{%
\section*{References}\label{references}}
\addcontentsline{toc}{section}{References}

\printbibliography[heading=none]

\end{refsection}

\clearpage
\renewcommand{\thefigure}{SI\arabic{figure}}
\setcounter{figure}{0}
\setcounter{page}{1}
\setcounter{section}{1}
\setcounter{subsection}{0}

\begin{refsection}

\hypertarget{supplementary-information}{%
\section*{Supplementary Information}\label{supplementary-information}}
\addcontentsline{toc}{section}{Supplementary Information}

\hypertarget{specification-of-element-ratio-based-regression-models}{%
\subsection{Specification of Element Ratio-Based Regression Models}\label{specification-of-element-ratio-based-regression-models}}

We applied several transformations to facilitate model fitting and defining prior distributions: The EAC\textsubscript{POM} and EDC\textsubscript{POM} values were divided by their maximal values (i.e.~after transformation all values were \(\le1\)) and a small constant of 0.05 was added to the scaled EDC\textsubscript{POM} values to facilitate convergence. All predictor variables were centered (such that their mean value is 0 and the model's intercept represents average samples) and scaled (such that their standard deviation is 1).\\
We used a Normal prior distribution with a mean of log(0.5) and a standard deviation of 0.1 amounting to a 95\%-confidence interval of the prior intercept on the link function scale of approximately 0.34 to 0.76 which loosely matched our expectations of the position of the samples' mean following our normalization procedure. We also assumed the slopes of the top regression model to be normally distributed with a mean of 0 and a standard deviation of 0.2. This expresses a vague prior knowledge, allowing both negative and positive slopes of different strength with equal probability, matching the scarce knowledge basis for the relation of the different bulk peat chemistry descriptors with the EAC (supporting figure \ref{fig:p-ppc-res}).\\
For the variance of the individual measurements an exponential distribution was assumed. For each sample, we estimated a separate variance. We set the scale parameter for the prior of each measurement such that an average measurement had an average prior standard deviation of around \(\SI{138}{\micro\mol\per\g\carbon}\) which corresponds approximately to the maximum standard error reported by \textcite{Aeschbacher.2012} for EAC measurements for various humic and fulvic acids using the same measurement procedure. Similarly, for the residual variance of the regression model an equivalent exponential distribution was assumed.

\hypertarget{mirs-based-regression-models}{%
\subsection{MIRS-Based Regression Models}\label{mirs-based-regression-models}}

Bayesian projection was performed using projpred (1.1.6) \autocite{Piironen.2019} with L1-search, five clusters for prediction, and no penalization during computation of projected coefficients \autocite{Piironen.2019,Piironen.2020}. The number of variables to include in the projected model was determined based on the expected sum of log predictive densities (ELPD) computed by pareto smoothed importance sampling (mimicking leave-one-out cross-validation) (PSIS-LOO), such that the ELPD of the projected model was at most one standard error smaller than that of the reference model. Even though PSIS-LOO estimates were biased for most of the models due to influential observations, this has been shown to have only small influences on the performance of the projection approach \autocite{Piironen.2020}.

\hypertarget{cross-validation}{%
\subsection{Cross-Validation}\label{cross-validation}}

During 10-fold CV, the data is split into ten folds, and the models are fitted to all combinations of the folds, leaving out one of the ten folds each time. The left out fold is then used as test data the model's prediction are compared to by computing the RMSE \autocite{Roberts.2017}. Peat core data typically have a nested structure (samples at different depths are nested within cores) in terms of their variability. To ensure independence of the test data, we used stratified random sampling to account for this structure \autocite{Roberts.2017} which resulted in folds with 3 to 8 samples. We did not account for the fact that nearby sites are not completely independent since this would have increased sample size differences between folds. Due to the relative large inter-site variability, even between nearby sites, we assumed that this effect is negligible.

\hypertarget{discussion-of-other-potential-mechanisms-how-decomposition-may-affect-peat-eac-and-edc}{%
\subsection{\texorpdfstring{Discussion of Other Potential Mechanisms how Decomposition may Affect Peat EAC\textsubscript{POM} and EDC\textsubscript{POM}}{Discussion of Other Potential Mechanisms how Decomposition may Affect Peat EAC and EDC}}\label{discussion-of-other-potential-mechanisms-how-decomposition-may-affect-peat-eac-and-edc}}

Different decomposition and other processes may further modify peat EAC\textsubscript{POM} and EDC\textsubscript{POM}. This may partly explain the observed variability in the relation of the EAC\textsubscript{POM} and EDC\textsubscript{POM} to peat chemistry and molecular structures. However, effects are yet not well explored and and we can therefore only provide hypotheses.\\
First, it is known that phenols and quinones can undergo different condensation reactions with other phenols/quinones \autocite{Hotta.2002,Johnson.2015,Bolton.2018,Zhao.2020} or nitrogen and sulfur containing functional groups \autocite{Bolton.2018,Olk.2006,Heitmann.2006,Yu.2016}. Such reactions may decrease the amount of phenols and quinones and hence decrease the EAC\textsubscript{POM} and EDC\textsubscript{POM}. Strong aerobic decomposition, intesified e.g.~by higher temperatures, higher pH values, a larger nutrient availability, and a larger fraction of labile OM, may promote such reactions because it can increase the DOM concentration \autocite{Bragazza.2007,Fenner.2011,Kang.2018c,Bowring.2020} which in turn is suggested to increase the occurrence of such condensation reactions \autocite{Hotta.2002,Johnson.2015}. However, we may not exclude that such reactions may also play a role under anoxic conditions. The negative relation of the EAC\textsubscript{POM} to polysubstituted aromatics (table \ref{tab:t-mir-sel}) may point towards such effects.\\
Second, intense aerobic decomposition may promote the disintegration of cell-wall structures \autocite{Tsuneda.2001}. This may increase the surface accessibility of polymeric phenols and quinones to enzymes that can break them down \autocite{Tsuneda.2001}. In addition, this may increase the frequency of the mentioned condensation reactions. Disintegration of cell-wall structures may therefore be an important process in the mineralization and transformation of polymeric phenols and quinones. The relation of the EAC\textsubscript{POM} and EDC\textsubscript{POM} to free OH groups and intramolecularly bonded OH groups, respectively, may be an indicator for this (table \ref{tab:t-mir-sel}).\\
Third, polysaccharides are typically mineralized at a faster rate than polymeric phenols and quinones, both under oxic and anoxic conditions \autocite{Benner.1984}. Since polysaccharides are not assumed to be redox-active, this may increase the EAC\textsubscript{POM} and EDC\textsubscript{POM} by residual enrichment of redox active moieties.\\
Finally, an additional factor that might increase the variability in relations between peat chemistry and the EAC\textsubscript{POM} and EDC\textsubscript{POM} is root ingrowth in (highly) decomposed peat. Roots that are relatively rich in polymeric phenols \autocite{Moore.2007,Scheffer.2000} may increase the EDC\textsubscript{POM} and EAC\textsubscript{POM} (under anoxic conditions predominantly the EDC\textsubscript{POM}) of (highly) decomposed peat. This may result in a relative large EAC\textsubscript{POM} and/or EDC\textsubscript{POM}, in spite of the bulk peat being (highly decomposed). This may explain the relative large EDC\textsubscript{POM}:EAC\textsubscript{POM} ratio for Touxi and Dongtu. Macrofossil data would have been helpful to answer this questions, but were not available for the samples under study.\\
Based on our results, it remains currently unclear if and to which extent these factors may change peat EAC\textsubscript{POM} and EDC\textsubscript{POM}, but they represent plausible mechanisms which may explain the variability to peat chemical properties, including molecular structures.

\hypertarget{discussion-of-the-predictive-performance-of-the-models}{%
\subsection{Discussion of the Predictive Performance of the Models}\label{discussion-of-the-predictive-performance-of-the-models}}

Several factors may cause the large variability in the predictions of both models for the EAC\textsubscript{POM} and the bias of the element ratio-based model.
We attribute the latter to the complex interactions between vegetation chemistry and decomposition, as described above, that results in non-trivial gradients across the H:C-O:C gradient. The MIRS-based model probably performs better because it can separate OM fractions representative for changes in the EAC\textsubscript{POM}. In addition, element ratios probably cannot fully resolve quinone structural changes that control peat EAC\textsubscript{POM}, whereas MIRS-based models can because MIRS allow to better separate variations in carbonyl groups and different OM fractions \autocite{Stuart.2005}.
The large residual uncertainties of both models may be due to the relatively small sample size in contrast to the broad gradient in peat chemical properties covered. On the one side, this results in large differences in peat chemistry the model has to describe, which lowers its predictive performance in comparison to more targeted models, and one the other side, the small sample size results in a relative large CV error. Finally, the electrochemical measurements itself have a relative large variability which we fully considered during CV. We therefore suggest that MIRS-based regression models may be at least suitable as screening tools. Furthermore, we suggest that additional data, different preprocessing methods, or modeling approaches (e.g.~local models depending on peat characteristics) may improve the predictive performance of a predictive model.\\
We believe that the reason for the low performance of the models for the EDC\textsubscript{POM} is the stronger dependence of phenols on decomposition, in addition to the general issues mentioned for models for the EAC\textsubscript{POM}. MIR variables indicative for phenols \autocite{Stuart.2005} typically are overlapped by other bands in peat MIRS. The stronger dependence on decomposition indicators (e.g.~the N:C ratio) probably makes the amount of carbonyl groups or aromatic backbone structures less suitable as predictors for the EDC\textsubscript{POM}, even though the correlation spectra indicated some relation (figure \ref{fig:p-mir-cor-res}). Similarly, indicators for fresh peat do not account for the fact that peat with large amounts of polysaccharides typically contain less polymeric phenols and therefore also may have a small EDC\textsubscript{POM}. Overall this likely makes predictions using linear methods or a global model difficult.\\
Bias from not considered contributions of iron to the EAC\textsubscript{POM} and EDC\textsubscript{POM} may also play a role, even though residual plots versus total iron content did not indicate patterns for the filtered data (supporting figures \ref{fig:reg-fe-res} and \ref{fig:cal-fe-res}).

\hypertarget{correlation-of-the-eac-edc-and-edceac-ratio-with-xrf-data}{%
\subsection{\texorpdfstring{Correlation of the EAC\textsubscript{POM}, EDC\textsubscript{POM}, and EDC\textsubscript{POM}:EAC\textsubscript{POM} Ratio with XRF Data}{Correlation of the EAC, EDC, and EDC:EAC Ratio with XRF Data}}\label{correlation-of-the-eac-edc-and-edceac-ratio-with-xrf-data}}

We measured element contents with wavelength dispersive X-ray fluorescence spectroscopy (WD-XRF; ZSX Primus II, Rigaku, Tokyo, Japan), but did not include the measurements into our analyses since such analyses are entirely explorative and not corrobated by similar analyses for DOM and HS. Here, we present Pearson correlation coefficients for the measured element contents with the EAC\textsubscript{POM}, EDC\textsubscript{POM}, and EDC\textsubscript{POM}:EAC\textsubscript{POM} ratio (table \ref{tab:t-cor-el-xrf}).

\begin{table}

\caption{\label{tab:t-cor-el-xrf}Pearson correlation between the EAC\textsubscript{POM}, EDC\textsubscript{POM}, and EDC\textsubscript{POM}:EAC\textsubscript{POM} ratio on the one side and element contents as determined by wavelength dispersive X-ray fluorescence spectroscopy.}
\centering
\begin{tabular}[t]{cccc}
\toprule
Element & EAC\textsubscript{POM} & EDC\textsubscript{POM} & EAC\textsubscript{POM}:EDC\textsubscript{POM}\\
\midrule
Na & -0.17 & -0.25 & -0.22\\
Mg & 0.15 & 0.01 & -0.13\\
Al & -0.31 & -0.45 & -0.28\\
Si & -0.25 & -0.40 & -0.24\\
P & -0.08 & -0.51 & -0.52\\
\addlinespace
Cl & -0.06 & 0.00 & -0.10\\
K & -0.31 & -0.55 & -0.35\\
Ca & 0.34 & -0.03 & -0.26\\
Ti & -0.25 & -0.38 & -0.20\\
Cr & -0.32 & -0.43 & -0.26\\
\addlinespace
Mn & 0.22 & -0.15 & -0.33\\
Fe & -0.29 & -0.61 & -0.42\\
Cu & 0.02 & -0.29 & -0.30\\
Zn & 0.23 & -0.03 & -0.14\\
As & 0.07 & -0.01 & -0.02\\
\addlinespace
Br & 0.22 & 0.27 & 0.00\\
Rb & 0.59 & 0.42 & 0.03\\
Sr & 0.23 & -0.07 & -0.31\\
Ba & -0.32 & -0.41 & -0.17\\
Pb & 0.08 & 0.00 & -0.02\\
\bottomrule
\end{tabular}
\end{table}

\clearpage

\hypertarget{supplementary-figures}{%
\subsection{Supplementary Figures}\label{supplementary-figures}}

Figure \ref{fig:p-fe-xrf-comparison-res} compares iron contents from acid extraction with total iron contents as measured with wavelength dispersive X-ray fluorescence spectroscopy.

\begin{figure}[H]

{\centering \includegraphics[width=0.5\linewidth]{001-paper-main_files/figure-latex/p-fe-xrf-comparison-res-1}

}

\caption{Scatterplot of total iron contents from acid extraction versus total iron contents from wavelength dispersive X-ray fluorescence spectroscopy. The diagonal line represents identical iron contents from both procedures.}\label{fig:p-fe-xrf-comparison-res}
\end{figure}

Figure \ref{fig:p-fe-contribution-abs-res} shows histograms of the calculated contributions of iron to the EAC and EDC and the potential contribution of iron to either the EAC or EDC. All iron quantities refer to iron from acid extracts of the samples. It is assumed that Fe\(^{3+}\) ions contribute one mol electrons to the EAC and that Fe\(^{2+}\) ions contribute one mol electrons to the EDC. However, the acid extraction of iron from organic rich samples results in redox equilibria between the OM and iron species which leads to an overestimation of Fe\(^{2+}\) over Fe\(^{3+}\). Therefore, the potential contribution gives the amount of electrons iron may contribute to the EAC or EDC if all iron was present as Fe\(^{3+}\) or Fe\(^{2+}\), respectively (\(\text{Fe}_\text{tot}=\text{Fe}^{3+} + \text{Fe}^{2+}\)). This gives an overview on what contribution iron may maximally have had to the EAC and EDC, assuming that the acid extraction enabled the quantification of all redox active iron moieties in the samples.

\begin{figure}[H]

{\centering \includegraphics[width=0.8\linewidth]{001-paper-main_files/figure-latex/p-fe-contribution-abs-res-1}

}

\caption{Histograms of the calculated contribution of iron to the EAC (left), the EDC (middle), or the potential contribution of iron to either the EAC or EDC (right) to each sample.}\label{fig:p-fe-contribution-abs-res}
\end{figure}

\clearpage

Figure \ref{fig:p-fe-corrected-uncorrected-res} shows plots of EAC and EDC values with potential contribution from total acid extracted iron subtracted in dependency of either the measured EAC or EDC or the EAC\textsubscript{POM} and EDC\textsubscript{POM} (EAC or EDC with contributions from Fe\(^{3+}\) and Fe\(^{2+}\), respectively, subtracted) for both the complete and filtered (potential contribution of iron to the EAC and EDC \(\le \SI{100}{\micro\mol\of\gram\carbon}\)).

\begin{figure}[H]

{\centering \includegraphics[width=1\linewidth]{001-paper-main_files/figure-latex/p-fe-corrected-uncorrected-res-1}

}

\caption{Plot of EAC or EDC values, where the potential contribution from iron had been subtracted ($\text{EAC} - \text{Fe}_\text{tot}$ or $\text{EDC} - \text{Fe}_\text{tot}$) versus $\text{EAC}_\text{POM}$ or $\text{EDC}_\text{POM}$ values (\textbf{A, B}; $\text{EAC}_\text{POM} = \text{EAC} - \text{Fe}^{3+}$ and $\text{EDC}_\text{POM} = \text{EDC} - \text{Fe}^{2+}$) or measured EAC or EDC values (\textbf{C, D}) for the complete data set (\textbf{A, C}) or the data set with only samples that have a maximum potential contribution of iron to the EAC or EDC $\le \SI{100}{\micro\mol\of\gram\carbon}$ (\textbf{B, D}). Different colours represent samples from different sites and error bars represent standard deviations computed from replicate measurements of the EAC and EDC, respectively. The grey diagonal line with intercept in $(0,0)$ represents identical values along both axes. The other grey line is a linear regression line fitted to the data points.}\label{fig:p-fe-corrected-uncorrected-res}
\end{figure}

\clearpage

Figure \ref{fig:p-fe-raw-iron} shows the relation between measured EAC and EDC values on the one side and iron content values from wavelength dispersive X-ray fluorescence spectroscopy measurements and acid extraction. No systematic relation between the EAC values and iron contents are visible. For the EDC, samples with higher iron content tend to have smaller measured EDC values.

\begin{figure}[H]

{\centering \includegraphics[width=1\linewidth]{001-paper-main_files/figure-latex/p-fe-raw-iron-1}

}

\caption{Scatterplots of the measured EAC and EDC versus iron contents measured with wavelength dispersive X-ray fluorescence spectroscopy (Fe\textsubscript{tot, XRF} in mass-\%) or from acid extraction (Fe$^{2+}$, Fe$^{3+}$, and Fe\textsubscript{tot} in \si{\micro\mol\per\gram\of\sample}). Error bars represent the standard deviation from replicate measurements for the EAC and EDC, respectively.}\label{fig:p-fe-raw-iron}
\end{figure}

\clearpage

Figure \ref{fig:p-fe-decomposition-res} shows iron content values versus decomposition indicators (N:C ratio and HI\textsubscript{1630/1090}).

\begin{figure}[H]

{\centering \includegraphics[width=0.55\linewidth]{001-paper-main_files/figure-latex/p-fe-decomposition-res-1}

}

\caption{Scatterplots of iron contents measured with wavelength dispersive X-ray fluorescence spectroscopy (Fe\textsubscript{tot, XRF} in mass-\%) or from acid extraction (Fe$^{2+}$, Fe$^{3+}$, and Fe\textsubscript{tot} in \si{\micro\mol\per\gram\of\sample}) in comparison to peat decomposition indicators (N:C ratio and HI\textsubscript{1630/1090}). The grey lines are regression lines fit to the samples.}\label{fig:p-fe-decomposition-res}
\end{figure}

\clearpage

Figure \ref{fig:reg-fe-res} shows scatterplots of the residuals of the element ratio-based regression models in dependency of the total iron content of the samples.

\begin{figure}[H]

{\centering \includegraphics[width=1\linewidth]{001-paper-main_files/figure-latex/reg-fe-res-1}

}

\caption{Plot of residuals versus total iron contents for the element ratio-based regression models with the complete data set (\textbf{A}) and the filtered data set (\textbf{B}, maximal potential contribution of iron to the EAC and EDC $\le\SI{100}{\micro\mol\per\gram\carbon}$). Columns contain plots for different modeling approaches and dependent variables (Gaussian or Student-t prior for slopes, EAC\textsubscript{POM} or EDC\textsubscript{POM} as dependent variable), and rows represent different predictor variable combinations (only H:C and O:C ratio or all element ratios). The red curves are LOESS smoothers fit to the samples.}\label{fig:reg-fe-res}
\end{figure}

\clearpage

Figure \ref{fig:cal-fe-res} shows scatterplots of the residuals of the MIRS-based regression models in dependency of the total iron content of the samples.

\begin{figure}[H]

{\centering \includegraphics[width=0.8\linewidth]{001-paper-main_files/figure-latex/cal-fe-res-1}

}

\caption{Plot of residuals versus total iron contents for the MIRS-based regression models with the complete data set (\textbf{A}) and the filtered data set (\textbf{B}, maximal potential contribution of iron to the EAC and EDC $\le\SI{100}{\micro\mol\per\gram\carbon}$). Columns contain plots for different dependent variables (EAC\textsubscript{POM} or EDC\textsubscript{POM}), and rows represent different modeling approaches (Bayesian regularization or PLSR as methods to compute regression models, using the non derived or first derivative of the mid infrared spectra as predictor variables, transforming the dependent variable (EDC\textsubscript{POM} only) by dividing it by HI$_\text{1630/1090}$). The red lines are LOESS smoothers fit to the samples.}\label{fig:cal-fe-res}
\end{figure}

\clearpage

Figure \ref{fig:el-preprocessing-p1-res} shows boxplots of the peat EAC\(_\text{POM}\) and EDC\(_\text{POM}\) replicate measurements for each sample.

\begin{figure}[H]

{\centering \includegraphics[width=0.5\linewidth]{001-paper-main_files/figure-latex/el-preprocessing-p1-res-1}

}

\caption{Boxplots of the EAC$_\text{POM}$ and EDC$_\text{POM}$ replicate measurements for the samples from this study. For sample 2, the EAC measurement with more than $\SI{1500}{\micro\mol\per\gram\carbon}$ was assumed to represent a measurement error and therefore discarded prior the statistical analysis.}\label{fig:el-preprocessing-p1-res}
\end{figure}

\clearpage

Figure \ref{fig:el-comparison-peatland-types-res} shows the peat samples' EAC\textsubscript{POM} and EDC\textsubscript{POM} values of all peat samples for each peatland site.

\begin{figure}[H]

{\centering \includegraphics[width=0.5\linewidth]{001-paper-main_files/figure-latex/el-comparison-peatland-types-res-1}

}

\caption{Plots of the EAC$_\text{POM}$ and EDC$_\text{POM}$ (average values of replicate measurements) for each peatland site and assigned to different peatland types following information from available studies for the respective sites (table ef{tab:t-study-sites}) or from own investigations following concepts in \textcite{Rydin.2013}.}\label{fig:el-comparison-peatland-types-res}
\end{figure}

\clearpage

Figure \ref{fig:p-reg-distogram-res} shows the structure of the Bayesian hierarchical regression models used to predict the peat EAC\textsubscript{POM} and EDC\textsubscript{POM} from element ratios, including the respective distributions \autocite{Kruschke.2015,Baath.2018}, using either Gaussian slopes or Student-t slopes.

\begin{figure}[H]

{\centering \includegraphics[width=\textwidth]{./../figures/rp_regression_distogram_tot}

}

\caption{Conceptual representation of the structure of the regression models \cite{Kruschke.2015, Baath.2018} using element ratios as predictor variables. A: Model structure for the models with normal distributed slopes. B: Model structure for the models with Student-t distributed slopes ($\nu = 6$). $y_i$ is the ith replicate EAC\textsubscript{POM} or EDC\textsubscript{POM} measurement. Replicate measurements for the same sample are assumed to follow a Gamma distribution with mean $\mu_j$ for the jth sample, and a sample-specific standard deviation $\sigma_j$. The $\mu_j$ are modeled by a regression equation $\exp\left(\beta_0 + \beta_1 x_1\right)$ and are also assumed to follow a Gamma distribution with mean $\mu$ and standard deviation $\sigma_2$. $\beta_0$ is the global intercept of the regression equation and is assumed to follow a normal distribution with mean $\mu_{\beta_0}$ and standard deviation $\sigma_{\beta_0}$. $\beta_1$ represents a regression slope for a variable $x_1$ (e.g. the H:C ratio). For each of the $k$ predictor variables ($k=2$ for the models with the H:C and O:C ratio as predictor variables, and $k=4$ for the models including in addition the N:C and S:C ratio), there is a seprate $\beta_k$ (not shown in the figure). The $\beta_k$ (e.g. $\beta_1$) are either assumed to follow a normal distribution (A), or a Student-t distribution (B) with mean $\mu_{\beta_1}$, standard deviation $\sigma_{\beta_1}$, and $\nu_{\beta_1}$ degrees of freedom.}\label{fig:p-reg-distogram-res}
\end{figure}

\clearpage

Figure \ref{fig:p-ppc-res} shows the prior predictive check for the slopes of potential predictor variables for the different modeling approaches for the element ratio-based models.

\begin{figure}[H]

{\centering \includegraphics[width=1\linewidth]{001-paper-main_files/figure-latex/p-ppc-res-1}

}

\caption{Prior predictive checks for the regression model using element ratio as predictor variables. Columns differentiate different modeling approaches (Gaussian or Student-t prior for slopes, all element ratios as preditor variables or only the H:C and O:C ratio), and rows represent different predictor variables. Lines are 100 random draws from the respective prior distributions.}\label{fig:p-ppc-res}
\end{figure}

\clearpage

Figure \ref{fig:p-y-yhat-reg-res} shows plots of measured versus fitted values for all computed element ratio-based regression models.

\begin{figure}[H]

{\centering \includegraphics[width=1\linewidth]{001-paper-main_files/figure-latex/p-y-yhat-reg-res-1}

}

\caption{Plot of measured versus fitted values (both in \si{\micro\mol\per\gram\carbon}) for the element ratio-based regression models with the complete data set (\textbf{A}) and the filtered data set (\textbf{B}, maximal potential contribution of iron to the EAC and EDC $\le\SI{100}{\micro\mol\per\gram\carbon}$). Columns contain plots for different modeling approaches and dependent variables (Gaussian or Student-t prior for slopes, EAC\textsubscript{POM} or EDC\textsubscript{POM} as dependent variable), and rows represent different predictor variable combinations (only H:C and O:C ratio or all element ratios). Error bars represent 95\% predictive intervals for the measured and predicted values. Points on the diagonal lines represents identical measured and fitted values.}\label{fig:p-y-yhat-reg-res}
\end{figure}

\clearpage

Figure \ref{fig:p-y-yhat-cal-res} shows plots of measured versus fitted values for all computed MIRS-based regression models.

\begin{figure}[H]

{\centering \includegraphics[width=0.8\linewidth]{001-paper-main_files/figure-latex/p-y-yhat-cal-res-1}

}

\caption{Plot of measured versus fitted values (both in \si{\micro\mol\per\gram\carbon}) for the MIRS-based regression models with the complete data set (\textbf{A}) and the filtered data set (\textbf{B}, maximal potential contribution of iron to the EAC and EDC $\le\SI{100}{\micro\mol\per\gram\carbon}$). Columns contain plots for different dependent variables (EAC\textsubscript{POM} or EDC\textsubscript{POM}), and rows represent different modeling approaches (Bayesian regularization or PLSR as methods to compute regression models, using the non derived or first derivative of the mid infrared spectra as predictor variables, transforming the dependent variable (EDC only) by dividing it by HI$_\text{1630/1090}$). Error bars represent 95\% predictive intervals for the measured and predicted values. Points on the diagonal lines represents identical measured and fitted values.}\label{fig:p-y-yhat-cal-res}
\end{figure}

\clearpage

Figure \ref{fig:p-el-eac-edc2-res} shows plots of the EDC versus the EAC for samples from this study and different HS and DOM samples from other studies.

\begin{figure}[H]

{\centering \includegraphics[width=0.5\textwidth]{001-paper-main_files/figure-latex/p-el-eac-edc2-res-1}

}

\caption{Plot of the average EAC versus the average EDC for peat POM samples of this study and DOM and HS samples from other studies. Error bars represent the respective standard errors from replicate measurements (only for this study). Samples below the diagonal line have a larger EAC than EDC.}\label{fig:p-el-eac-edc2-res}
\end{figure}

\clearpage

Figure \ref{fig:p-cal-elpd-res} shows plots of the expected sum of log predictive densities (ELPD) estimated by PSIS-LOO \autocites[ ]{Piironen.2020}{Piironen.2019} for the MIRS-based regression models (reference models) and the projected models.

\begin{figure}[H]

{\centering \includegraphics[width=0.65\textwidth]{001-paper-main_files/figure-latex/p-cal-elpd-res-1}

}

\caption{Plot of the expected sum of log predictive densities (ELPD) for the MIRS-based regression models (reference models) and the projected models with the complete data set (top row) and the filtered data set (bottom row, maximal potential contribution of iron to the EAC and EDC $\le\SI{100}{\micro\mol\per\gram\carbon}$). Points reresent the average ELPD, and error bars its standard error. The y axis differentiates modeling approaches (Bayesian regularization or PLSR as regression model, not derived or first derivative of spectra as predictor variables, transformation of the EDC by division by HI$_\text{1630/1090}$). Note that the ELPD values are biased since not for all models the underlying assumptions were met.}\label{fig:p-cal-elpd-res}
\end{figure}

\clearpage

Figure \ref{fig:p-partial-dependence-res} shows plots of the expected sum of log predictive densities (ELPD) estimated by PSIS-LOO \autocites[ ]{Piironen.2020}{Piironen.2019} for the MIRS-based regression models (reference models) and the projected models.

\begin{figure}[H]

{\centering \includegraphics[width=0.8\linewidth]{001-paper-main_files/figure-latex/p-partial-dependence-res-1}

}

\caption{Partial dependence plots for groups of variables included in the projected MIRS-based regression model for the EAC\textsubscript{POM} (with Bayesian regularization and not derived spectra) computed with the complete data set (\textbf{A}) and the filtered data set (\textbf{B}, maximal potential contribution of iron to the EAC and EDC $\le\SI{100}{\micro\mol\per\gram\carbon}$). This is the model interpreted in the main text. Each panel contains the plots for one OM group (labile, lipids, aromatics, carbonyl), and each panel's subplots the respective variables indicated by their wavenumber values (for example MIR variables assigned to labile OM fractions are those at 3660 and \SI{3670}{\wn}). The partial dependence plots were created by predicting EAC\textsubscript{POM} values with the projected models for the input data, where all variables except those in the respective OM groups were set to their average value. Black points represent these predictions. Grey points represent the respective measured EAC\textsubscript{POM}. Error bars represent the 95\%-posterior intervals for the average (predicted values) and individual observations (for the measured values), respectively.}\label{fig:p-partial-dependence-res}
\end{figure}

\clearpage

Figure \ref{fig:conceptual2} is a conceptual representation of the interactions between vegetation chemistry and decomposition on peat POM electrochemical properties as mediated by its chemistry.

\begin{figure}[H]

{\centering \includegraphics[width=1\linewidth]{./../figures/conceptual_vegetation_decomposition2}

}

\caption{Conceptual graphic showing the assumed effects of vegetation chemistry (polymeric phenol content) and decomposition pathways and intensity on peat chemistry and its EAC\textsubscript{POM} and EDC\textsubscript{POM}. Circles represent from left to right phenols, quinones, polysaccharides, and non-redox active OM fractions (condensed aromatics, lipids). Their area represents the absolute fraction of these moieties. Barplots represent the absolute EDC\textsubscript{POM} and EAC\textsubscript{POM}.}\label{fig:conceptual2}
\end{figure}

\hypertarget{supplementary-references}{%
\section*{Supplementary References}\label{supplementary-references}}
\addcontentsline{toc}{section}{Supplementary References}

\printbibliography[heading=none]

\end{refsection}

\clearpage

\begin{figure}[H]

{\centering \includegraphics[width=0.6\textwidth]{./../figures/graphical_abstract}

}

\caption{Description: This study addresses the relation between peat chemical properties (element contents, mid infrared spectra) and electrochemical properties and the role of decomposition for both based on a global data set. Peat electrochemical properties (electron accepting capacity - EAC, electron donating capacity - EDC) control peatland methane formation. Phenols are main contributors to the EDC and quinones to the EAC. Vegetation chemistry and intensity of decomposition are major controls of peat EAC and EDC. Peat with initial large amount of phenols initially have a large EDC and upon decomposition a larger EAC since phenols are transformed to quinones. Samples with initially smaller amount of phenols cannot attain the same EAC/EDC levels, even though decomposition leads to similar changes. This conceptual model can explain the large within and between-site variability of the EAC and EDC we observed, as well as the complex relations to indicators of peat chemistry and decomposition indicators.}\label{fig:graphical-abstract}
\end{figure}

% Submissions are not required to reflect the precise reference formatting of the journal (use of italics, bold etc.), however it is important that all key elements of each reference are included.




\end{document}
