---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# packages
library(magrittr)
library(dplyr)
library(bib2df)
library(tinytex)
```


```{r}
# clean the bib file
# get bibkeys
bibkeys <- bib2df::bib2df("references.bib")

# get texts to search for bibkey
si_text <- 
  readLines("006-paper-supplementary.Rmd") %>%
  paste(collapse = " ")
  
main_text <- 
  readLines("001-paper-main.Rmd") %>%
  paste(collapse = " ")

# filter
bibkeys <-
  bibkeys %>%
  dplyr::mutate(
    refs_target = 
      purrr::map_lgl(BIBTEXKEY, function(x) {
          (stringr::str_detect(si_text, x) | stringr::str_detect(main_text, x)) 
      }),
  )

bibkeys %>%
  dplyr::filter(refs_target) %>%
  dplyr::select(-refs_target, -FILE.1, -FILE.2, -FILE.3) %>%
  dplyr::mutate(KEYWORDS = NA, FILE = NA) %>%
  bib2df::df2bib("references.bib")
```


```{r}
# fully compile literature references in main document
tinytex::latexmk(file = "001-paper-main.tex", clean = FALSE)
system("bibtex si.aux")
tinytex::latexmk(file = "001-paper-main.tex", clean = FALSE)
```

```{r}
# remove unnecessary parts in supplementary information
si <- readLines("006-paper-supplementary.tex")

index_keypoints <- stringr::str_detect(si, "^\\\\begin\\{keypoints\\}")
index_absract <- stringr::str_detect(si, "^\\\\begin\\{abstract\\}")

si <- si[-c(which(index_keypoints) + 0:2, which(index_absract) + 0:2)]

writeLines(si, "006-paper-supplementary.tex")

tinytex::latexmk(file = "006-paper-supplementary.tex", clean = FALSE)
```

