// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;


RcppExport SEXP _rcpp_module_boot_stan_fit4rp_regression_base_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4rp_regression_gamma1_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4rp_regression_gamma1_prior_check_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4rp_regression_gamma2_student_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4rp_regression_gamma2_student_prior_check_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_stan_fit4rp_regression_base_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4rp_regression_base_mod, 0},
    {"_rcpp_module_boot_stan_fit4rp_regression_gamma1_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4rp_regression_gamma1_mod, 0},
    {"_rcpp_module_boot_stan_fit4rp_regression_gamma1_prior_check_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4rp_regression_gamma1_prior_check_mod, 0},
    {"_rcpp_module_boot_stan_fit4rp_regression_gamma2_student_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4rp_regression_gamma2_student_mod, 0},
    {"_rcpp_module_boot_stan_fit4rp_regression_gamma2_student_prior_check_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4rp_regression_gamma2_student_prior_check_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_redoxpeat(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
